### ISSUE TITLE
Cover VIC-II register D018 / 53272

### ISSUE THREAD

**Issue by sausagejohnson** [MEGA65/mega65-user-guide#104]
Explain why we peek it, what the values are for, what we can do with it,

**Comment by gardners** [comment]
Please remind me of the context for this.  What programme were you looking at?

**Comment by sausagejohnson** [comment]
53272 is used in many of our listings to check bit 5 if we are running in C64 or C65 mode. But nowhere in the current documentation is this register and its many uses explained as yet.

**Comment by gardners** [comment]
ah, gotcha. It is used in the normal C64 way to check the screen address. The test relies on the screen in C65 mode being at $0800 rather than $0400.

Paul.

**Comment by gardners** [comment]
Documented.
