### ISSUE TITLE
PI requires a space before it in screenoutput environment, or else it appears in weird places

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#11]
Is it possible to display the PI character in the screenoutput environment?

At the moment, if you don't have a space before it, it appears much earlier in the line.
See the command reference for ATN in the BASIC 10 appendix for an example of this problem.

**Comment by Edilbert** [comment]
This issue was not related to pi, but to the preceding character '/', which needs a literate entry in the lstset definition.
