### ISSUE TITLE
List "Essential files" alphabetically, as per scryptos, page 6

### ISSUE THREAD

**Issue by Ben-401** [MEGA65/mega65-user-guide#112]
When comparing the list of files in the PDF to the list of files on scryptos, Id prefer to see the same order. Seems one file is missing as it is listed in PDF but is not on scryptos. File missing on scryptos is MEGA65.D81

**Comment by deftmega** [comment]
Fixed. I also added the default megaWAT?! font "DEFAULTP.FPK" and removed ancient links to fileset and bitstream on MEGA65.org

**Comment by gurcei** [comment]
Ok, sounds like this is sorted, so closing the ticket.
