### ISSUE TITLE
Somewhat confusing description and notions of "fast" and "slow" mode

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-user-guide#115]
The book says: "Slow (1MHz – 3.5MHz) Operation" and "Full Speed (40MHz) Instruction Timing". I don't agree with this, 3.5MHz is "C65 fast" and 40 is "MEGA65 fast", slow is only 1MHz (and I guess maybe 2MHz is that too, but also called "C128 fast" ...).

Note that this is not just the notions are problematic, but the book states: "In these modes, opcodes take the same number of cycles as an 6502" for the "Slow (1MHz – 3.5MHz) Operation". I think it's wrong, in C65 fast mode (3.5MHz) the timing is NOT the same as in 1MHz (slow) mode.

But this is just an example, other problems may come since 3.5MHz is considered "slow" so it's treated the same way as the 1MHz speed, which shouldn't be done this way, slow is only 1MHz (or maybe 2MHz too), 3.5MHz is not, it has different timing etc.

I would rather modify this to have "slow" which should be 6502 timing compatible, "c65 fast" which is 4510/65CE02 timing compatible (c65 native speed, it's true that MEGA65 still needs to be slowed down for this, but not the same way as for 1MHz!), and "mega65 fast", which is the "top" or "native" speed/timing of MEGA65. The 2Mhz mode (IIRC ....) is really like 1MHz in timing (is it true???) just faster, so it's a question that it can be called slow mode, or can be called "C128 fast" mode, but I think, this should be not a question for 3.5MHz, which is definitely cannot be one category with the "1MHz slow" mode.

So, I think, there are at least three timings (not clock speeds, timings) in MEGA65: the 6502-behaviour (for 1MHz and maybe 2MHz too?), the c65-behaviour (3.5Mhz) and the full speed MEGA65 behaviour (40+ MHz). I don't know if it's possible to set 6502 "cpu persona" for eg 3.5MHz, btw, it does not make too much sense and would break things (like 1 cycle opcodes does not allow interrupt after them, but in 6502-like persona, there is no 1 cycle op ... etc).

I am not sure this slow/fast issue appears at other parts of the book as well other than what I found and discussed.

**Comment by anshul-birajdar** [comment]
yaa!

**Comment by gardners** [comment]
Yes, you are right LGB, that there are three different instruction timings that apply: 1/2MHz, 3.5MHz and 40.5MHz.

**Comment by Edilbert** [comment]
The new SPEED commands accepts an argument in MHZ (1, 3 or 40), so this issue is solved.
