### ISSUE TITLE
Making PDF files available through releases

### ISSUE THREAD

**Issue by isedwards** [MEGA65/mega65-user-guide#116]
Would someone be happy to make occasional GitHub code releases and include the latest version of the PDFs with the release for easy downloading?

**Comment by isedwards** [comment]
I've just seen the PDF in amongst the code files (I'm browsing on my phone  so I didn't notice straight away...)

I'll leave this issue open in case using releases makes sense. There could also be a link to the releases in the main `README.md` so that it's obvious that a PDF is available.

**Comment by sausagejohnson** [comment]
I'll add a link from the readme. Good pickup.

**Comment by gardners** [comment]
We'll also start putting the PDF on files.mega65.org fairly soon, I think, which will be the better place for it, rather than having binary blobs under source control.

**Comment by isedwards** [comment]
I'd argue that it would be worth making occasional GitHub releases, and storing the binary PDF file as part of the release, in order to ensure that versions of the PDF are always kept with the repository where it was created (incase `files.mega65.org` ever moved or was decommisioned).

Here's an example from another LaTeX repository: https://github.com/HugoForrat/LaTeX-Vim-User-Manual/releases

- Step 7 in the article below shows attaching binary files
- Step 8 shows the option of marking the release as a "pre-release"

https://docs.github.com/en/enterprise/2.13/user/articles/creating-releases

**Comment by gardners** [comment]
Yes, I've been meaning to get around to this for a while.  Now done.
