### ISSUE TITLE
Needed explanation regarding CPU speed

### ISSUE THREAD

**Issue by FeralChild64** [MEGA65/mega65-user-guide#125]
On MEGA65 there are several ways (I know 7, but there might be more..) to alter the CPU speed:

- CAPS LOCK pressed by the user forces the CPU to run fast - but this behaviour can be changed within the hypervisor
- IEC bus activity forces the CPU to run at 1 MHz for some time
- there is a 6 (VFAST) bit in $D054 (VIC control register C) which, according to current documentation, enables 48 MHz mode, but according to information from XEMU author this is more complicated and one has to apply additional settings (see [here](https://www.forum64.de/index.php?thread/104591-xemu-vic-iv-implementation-update/&postID=1575918#post1575918))
- there is a POKE 0,64 / POKE 0, 65 method
- there is a C128-compatible C128FAST bit in $D030 VIC-II personality to set 2 MHz mode
- there is a C65-compatible FAST bit in VIC-III/VIC_IV personalities in $D031 register to set 3.5 MHz mode
- the hypervisor can force 48MHz mode in $D67D

It's hard to get precise information, it's all scattered across the documentation and probably incomplete. I propose to add a new chapter, similar to the existing CPU MEMORY BANKING chapter, which would:

1) describe each method to change the CPU speed (including the VFAST bit explanation - is setting the bit enough to trigger 48 MHz mode, or something more is needed?)
2) provide a table or a clear "setting priority" information, so that for ANY combination of the settings above we will be able to tell:

- what the resulting CPU speed (in terms of MHz) will be
- whether 6502-compatible or MEGA65 CPU instruction timing (cycles per instruction) will be used
- whether it is safe to use compound instructions if IRQ or NMI interrupt might happen

**Comment by lgblgblgb** [comment]
I think it's a very important question, maybe a table or something like that would be needed to list all the CPU speeds and how to set that (to my best knowledge there are three bits M65FAST, C65FAST and C128FAST and their combination determines the actual speed - though I admit I use my own notions for these bits not the "official"), what kind of exact CPU clock you'll get, and indeed how opcode timing is affected (I guess SLOW and C128 FAST are actually NMOS timing 1/2MHz, 3.5Mhz C65FAST has the 65CE02 timing already, and M65FAST has additional effects on timing resulting around 40MHz of CPU clock). I have no idea about the "CPU clock fine-tune" stuff, I've once spotted somewhere though).

It would be also important to really use the notions of "slow" and "fast" mode in a consistent way, I had problems with that, see: #115

**Comment by FeralChild64** [comment]
BTW, there is a typo in the SPEEDBIAS address; should be $D7FA, not $F7FA.

**Comment by Edilbert** [comment]
typo fixed.
The new BASIC commands SPEED and RSPEED make setting and reading of the CPU speed easy.
