### ISSUE TITLE
Program generated file "api-conio.tex" crashes the LaTeX build

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-user-guide#127]
The program, that generates the file "api-conio.tex", writes some illegal LaTeX code,
which causes fatal errors during the LaTeX run and stops creating the pdf after ca. 200 pages.

**Comment by hernandp** [comment]
I'm fixing this now.  A problem I had is that I cant embed LaTex tables into `\begin{description}` blocks.  Maybe I'm a bit of a noob.

**Comment by Edilbert** [comment]
Hello Hernán,

here is an example with a table inside a desription block.
You may find many examples, that you can use as a template in the file:

appendix-basic10.tex

and feel free to ask, I'm happy to help.

Best wisshes,
Edilbert

----------------------------------------------------------------------
\newpage
\subsection{BACKGROUND}
\index{BACKGROUND}
\index{BASIC 10 Commands!BACKGROUND}
\begin{description}[leftmargin=2cm,style=nextline]
\item [Token:] \$FE \$3B 
\item [Format:] {\bf BACKGROUND colour}
\item [Usage:] Sets the background colour
               of the screen to the argument, which must be in the
               range 1 to 16. (See colour table).
\item [Colours:] {\bf Index and RGB values of colour palette}

\ttfamily
{\setlength{\tabcolsep}{1mm}
\begin{tabular}{*{4}{|R{1.2cm}}|l|}
\hline
 index  &   red & green & blue & colour \\
\hline
  1 &    0  &   0   &  0   & black \\
  2 &   15  &  15   & 15   & white \\
  3 &   15  &   0   &  0   & red   \\   
  4 &    0  &  15   & 15   & cyan  \\
  5 &   15  &   0   & 15   & magenta\\
  6 &    0  &  15   &  0   & green \\
  7 &    0  &   0   & 15   & blue  \\
  8 &   15  &  15   &  0   & yellow\\
  9 &   15  &   6   &  0   & orange\\
 10 &   10  &   4   &  0   & brown \\
 11 &   15  &   7   &  7   & pink  \\
 12 &    5  &   5   &  5   & dark grey\\
 13 &    8  &   8   &  8   & medium grey\\
 14 &    9  &  15   &  9   & light green \\
 15 &    9  &   9   & 15   & light blue\\
 16 &   11  &  11   & 11   & light grey\\
\hline
\end{tabular}
}
\item [Example:] Using {\bf BACKGROUND}
\begin{tcolorbox}[colback=black,coltext=white]
\verbatimfont{\codefont}
\begin{verbatim}
BACKGROUND  4 : REM SELECT BACKGROUND COLOUR CYAN
\end{verbatim}
\end{tcolorbox}
\end{description}

**Comment by hernandp** [comment]
I think that the problem is that the libc-doc converter we use bails out when it detects a closing brace "}" so for the following embedded comment in the H file:

```
    \m65libparam     {format}{The string to output. The available escape codes are: \\
    \begin{tabular}
    \end{tabular}
    }
```

It will bail-out after \begin{tabular} not allowing to embed LaTeX expressions there.

**Comment by hernandp** [comment]
@gardners probably we can patch the libc-doc converter to e.g. assume that between some set of characters (e.g: "%<" and "%>") or similar, it should dump _literally_ the LaTeX text, so we can embed a code without { and } braces interfering. What do you think.

**Comment by gardners** [comment]
Yes, that is fine with me.  Did you want to do the change, or would you like me to do it?

**Comment by hernandp** [comment]
> Yes, that is fine with me. Did you want to do the change, or would you like me to do it?

Thanks Paul, i'll appreciate very much if you can hack up the converter as I should finish some work tomorrow first.

**Comment by gardners** [comment]
I believe the above commit implements this for you.

**Comment by hernandp** [comment]
Guys, the commit at https://github.com/MEGA65/mega65-libc/commit/45e82a587b8f5d68f9bbce7a0399561583104aeb should fix this issue and emit a nice output for the problematic cprintf function.

@gardners  I noticed now that the libc-doc utility needs a small patch where "desription" is printed instead of "return value", at line 99 it should read:

```
	printf("\\item [Return value:] {%s}\n",token);
```

Thanks.

**Comment by Edilbert** [comment]
Works fine now.
Thanks to all.
