### ISSUE TITLE
Prep for first use: formatting SD cards - can computer start if no formatted SD card is present in slot 0 or 1?

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#129]
End of page 24 has this remark:

"For safety when formatting we strongly recommend that you remove any SD card or microSD card that you do not intend to format"

Is this correct, will the computer be able to start with no internal SD card in slot 1 and an unformatted/new microSD in slot 0?
I thought that at least in one of the slots a formatted SD card needs to be present to be able to boot.

**Comment by gardners** [comment]
Yes, you can get to the utility menu with no SD card, as its all in the bitstream that you need to format the SD card.

**Comment by MauriceMEGA65** [comment]
That sounds good!
Maybe we should put a note in the manual that the Utility menu is accessible without any SD card installed?
Unless it's only me who has this question ;-)

**Comment by gardners** [comment]
Yes, probably a good idea.  Find where in the user guide you think this reference should be, and search through the .tex files (which are basically plain text with markup) to find where that would be, and have a go making a pull request with the extra sentence. We can deal with any formatting dramas.

Paul.

**Comment by MauriceMEGA65** [comment]
Done
