### ISSUE TITLE
Wrong PETSCI code in manual

### ISSUE THREAD

**Issue by adtbm** [MEGA65/mega65-user-guide#132]
In the manual page 403 "PETSCII CODES AND CHR$" is the switch off Lower / Uppercase by Print Chr$(8). But correct is Print chr$(11).

Disable Run/Stop - Poke 808,225
Enable Run/Stop - Poke 808,193

**Comment by Edilbert** [comment]
Thanks, I fixed the PETSCII table.
Currently we have no PEEKS & POKES chapter.
Or do you suggest, that we include your Run/Stop pokes into the keyboard chapter?

**Comment by adtbm** [comment]
Hi Edilbert, 
i've just created the issue out of a post in F64. So i think, fixing the the table solved the issue. Thanks !
really not sure, if we should create such a thing as a PEEK & POKE section, it could be interesting nevertheless

**Comment by gardners** [comment]
I think the POKEs could go into a "BASIC 10 Tips and Tricks" chapter
