### ISSUE TITLE
Incorrect and additional command

### ISSUE THREAD

**Issue by umueller-wsw** [MEGA65/mega65-user-guide#133]
The command RCLR(color source) returns a syntax error.
The RWINDOW(n) command is not documented in the manual. But it works analog to C128 mode Basic 7.0.

**Comment by Edilbert** [comment]
Thanks for the hint.
The function RCLR(n) was renamed to RCOLOR(n) for the C65 and is now documented as RCOLOR.
The RWINDOW(n) is already documented (alphabetically between RUN and SAVE)
