### ISSUE TITLE
Errors in assembly snippets for dma controller use

### ISSUE THREAD

**Issue by woepaul** [MEGA65/mega65-user-guide#140]
The code for pushing the `dmalist` address into `$D700-$D701` looks wrong. See
https://github.com/MEGA65/mega65-user-guide/blob/aa53f224943e217b7d12158397b1948cf1b2fcaa/appendix-dmagic.tex#L192-L195 Instead shouldn't it be
```
  LDA #>dmalist  ; Set MSB of DMA list address
  STA $D701 
  LDA #<dmalist  ; Set LSB of DMA list address, and execute DMA
  STA $D700
```
(Note the `#<dmalist` in the second store) The same mistake can also be found later:
https://github.com/MEGA65/mega65-user-guide/blob/aa53f224943e217b7d12158397b1948cf1b2fcaa/appendix-dmagic.tex#L219 and https://github.com/MEGA65/mega65-user-guide/blob/aa53f224943e217b7d12158397b1948cf1b2fcaa/appendix-dmagic.tex#L257

@gardners please let me know if this is really a bug in the example or if I'm misinterpreting the assembly syntax.

**Comment by gardners** [comment]
Well spotted. This is indeed an error.
