### ISSUE TITLE
Inconsistency in how to use MONITOR

### ISSUE THREAD

**Issue by jesperrula** [MEGA65/mega65-user-guide#143]
According to the user manual one can exit the MONITOR using E (for Exit). That hotkey is not listed in the monitor as a valid key and it does not work.

**Comment by gardners** [comment]
Thank you.

Bonus points if you feel brave enough to try making a pull-request with the required change in it :)

**Comment by Edilbert** [comment]
The manual describes this function as 'X' (for eXit).
Where did you see an 'E' listed for this function?

**Comment by jesperrula** [comment]
Honestly, I cannot find it. I think you should close this issue. In the future I will do a better job of documenting my findings.
