### ISSUE TITLE
M65 tool: Describe new -q option

### ISSUE THREAD

**Issue by sy2002** [MEGA65/mega65-user-guide#147]
### Enhance the M65 chapter / describe the new -q option

With commit https://github.com/MEGA65/mega65-tools/commit/35b336c625a311c0625e42f1a5620e1d9566de01 I added a new feature to the M65 tool: the -q option

The -q option is identical to the -b option as it flashes/downloads a new bitstream to the MEGA65. But in contrast to the -b option, the -q option is ending M65 after the download.

Always use -q instead of -b when you flash any other bitstream than the original MEGA65 bitstream, such as the ZX Uno bitstream or the Game Boy bitstream

**Comment by gurcei** [comment]
Done
