### ISSUE TITLE
LOADIFF BASIC 10 command not documented

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#155]
When it is documented, we should also document that the following commands can be used on Linux to produce compatible images for the LOADIFF command:

```
convert <myImage.jpg> <myImage.ppm>
ppmtoilbm -aga <myImage.pbm> > <myImage.iff>
```

(Thanks to @ubik on Discord for providing the commands above.)

**Comment by Edilbert** [comment]
documented.
