### ISSUE TITLE
Addition of an Appendix for Binary, Decimal and Hexadecimal

### ISSUE THREAD

**Issue by mds75** [MEGA65/mega65-user-guide#16]
I would like to add a section on binary, decimal and hexadecimal as another Appendix.
(This was originally described under Sprites in the C64 user manual 2nd edition but I think that because it is of general application it should go in the appendix.)

This would include:

- Description of why numbers are used in the first place
- Overview of binary, decimal and hexadecimal
- How to convert between each
- Bitwise logical operations, what they mean, what they do and how to set and clear bits

Optionally, I would like to include a type-and-run interactive BASIC 10 program that does numeric conversions for the user. (It would also do conversion on a range of numbers.) Also I think that a reference table that lists numbers between 0-255 in decimal, binary and hexadecimal would be very useful. 

I've gotten a head-start on these things already, but I though I'd better raise an issue for comment. Do people think that this would be useful to include? If so, I'll be happy to do it.

**Comment by Edilbert** [comment]
There are 10 types of people, those who understand binary and those who don't.
So I think it's important to write an appendix for the other type of people.
So go ahead, it will be a useful contribution.
We should also include all the other typical manual stuff, like ASCII table, PETSCII table, token table, keywords, etc.

**Comment by mds75** [comment]
Yes, we should. Perhaps I'll write an Appendix for the binary, hex and decimal and then have a separate Appendix called Reference Tables that will include all useful tables. It's all easy stuff to do, but it will be useful for beginners and those who haven't done low-level coding in a while.

**Comment by gardners** [comment]
Completely agree that we want this material. What is important is to avoid giving the impression that it is "hard".  This may require quite extensive material to ease people through the concepts.  Will certainly require lots of worked examples.

**Comment by mds75** [comment]
I've just created a pull request for my decbinhex branch which contains an updated userguide.tex and two new appendixes: appendix-decbinhex-tutorial.tex and appendix-reference-tables.tex. If someone could help to proofread this for errors and make suggestions for improvement, that would be great.  The computer program included is entirely optional as to whether we keep it or not. Thanks.

Sorry, first time I've used git and github :)

Mark

**Comment by gardners** [comment]
Hello,

Thanks - I'll take a look.

Paul.

**Comment by Edilbert** [comment]
Thank you very much, Mark.
Your text is well written and appreciated.
It's included in the book, so I think we can close this issue now.
You're welcome to contribute more of these fine chapters.
Edilbert

**Comment by mds75** [comment]
Hi,

 

Thanks for the praise. 😊

 

I’m glad you’ve found a use for it.

 

Anyway, I have some more spare time over the next few months. I can help out again. Do we have a list of outstanding chapters or features that we’d like to include in the user manual?

 

Depending on the level of c65-expertiese required I can contribute another chapter or two. Alternatively, I can read through and proofread what’s already there and give some more feedback on what I think needs improving or updating.

 

I haven’t kept my local repository up to date so I don’t know where we are up to at the moment… 

 

Thanks again,

 

Mark

**Comment by gardners** [comment]
Hi Mark,

We don't have a full list of what is missing yet.  Maybe you can take a look at what is there, and suggest what YOU think is missing.  This will help us to make it really user-oriented.

Paul.
