### ISSUE TITLE
GOSUB basic example

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#160]
Line 90 is missing a REM statement, but apparently the interpreter is not complaining about it(?)

**Comment by Edilbert** [comment]
Line 90 is not a target and will never be executed, so it will not produce an error.
I added a REM before however, because it's good practise to make clear, it's a comment line.
Your version has a typo in line 30:
IF D THEN ... is wrong, the correct statement is:
IF DD THEN ...
