### ISSUE TITLE
Add @Amok's "Install Vivado" steps

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#168]
[installvivado.zip](https://github.com/MEGA65/mega65-user-guide/files/6535313/installvivado.zip)

**Comment by gurcei** [comment]
I'll assign myself to this. Gathering and absorbing his body of work at the moment, available at:
- https://drive.google.com/drive/folders/1gCMJYNMlzHUNEyNNFBCIPwh8zOnVaL__?usp=sharing

He has made a few attempts at texifying, so also assessing how they have fared.

Also having a read through the entire mega65-book, to get a better feel for what is where, and get a sense of where his material best belongs. I think Paul and Amok might have had discussions on this topic in Discord somewhere, so I'll try re-read the thoughts shared there.

**Comment by gardners** [comment]
Thanks for taking it on, and with such a thorough approach :)

**Comment by gurcei** [comment]
Ok, for this ticket, I'll just be tackling the "Install Vivado" steps, as that proved to be quite an undertaking in itself, and can aim to tackle the other sections in future tickets.
