### ISSUE TITLE
broken links to bitstream and fileset.7z

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#172]
In the "PREPARING MICROSDHC CARD", they mention the following links:

- Bitstream http://mega65.org/assets/bitstream.7z
- Support Files http://mega65.org/assets/fileset.7z

Bot these links give me a "Not Found" error.

**Comment by gurcei** [comment]
Pinging @frehwagen and @deftmega on this topic, in-case they're familiar with how these files get prepared on the mega65.org filehost.

Is it done manually? Or automated by Jenkins?

**Comment by gardners** [comment]
Hello,

I think the .7z files were manually prepared. I don't think we have an
official automatic release process for them. We should think about what
would be simple enough to be maintainable, and also effective.

Paul.

**Comment by gurcei** [comment]
While reading through Amok's docs today, I noticed he provided a link to the new filehost instead, maybe that's the way to go?
```
https://files.mega65.org/files/s/SDessentialsNoROM_LMihuR.rar
```

There's a bit of hashy-noise at the end of the link though (I suppose to distinguish between newer versions that get uploaded?), so perhaps the link would need to get updated all the time, to assure it points to the latest?

Perhaps another option could be to point them to the old filehost, with links like this?

https://mega.scryptos.com/sharefolder-link/MEGA/MEGA65+filehost/Bitstreams/Jenkins-Out/mega65-core/development/78-73a2cab/

https://mega.scryptos.com/sharefolder-link/MEGA/MEGA65+filehost/Bitstreams/Jenkins-Out/mega65-core/development/78-73a2cab/sdcard-files

**Comment by gardners** [comment]
Ask Deft the right way to do handle this, if you haven't already.

**Comment by gurcei** [comment]
Some discussions underway with Deft, Tayger and Falk.

Tayger explained that there are plans for Falk to auto-upload to the new filehost in future, just they haven't gotten around to it yet.

So my present approach will be more an interim stop-gap until these auto-uploads occur.

# Replacing: "Bitstream http://mega65.org/assets/bitstream.7z"

This is now replaced with a link to the old filehost, along with an explanation of how to retrieve the latest bitstream files from there.

https://mega.scryptos.com/sharefolder-link/MEGA/MEGA65+filehost/Bitstreams/Jenkins-Out/mega65-core/development/

In future, when @frehwagen and Tayger settle on their automated upload mechanism, perhaps all .bit files (and all .cor files too?) will be pushed to the new filehost as a single "bitstreams.7z" file, and the documentation can link to that specific download-page.


# Replacing: Support Files http://mega65.org/assets/fileset.7z

For my first attempt at this, I've used a direct link to the new filehost, for the "**MEGA65 SD card essentials - No ROM**"  download is located:

https://files.mega65.org?id=0fb941fe-5c5f-4608-b0f1-32849d4a8dff

Tayger did ask whether it was worth also making end-users aware of the other download location that contains the closed-rom, "**MEGA65 SD card essentials**";

https://files.mega65.org?id=a809e0ae-30ac-42f5-ab9c-766d72fd6331

I'll aim to make a mention of this option too.

# Future automations needed

1) Auto-upload of latest .bit and .cor files after every successful Jenkins build (perhaps all zipped up into single file) to the new filehost

2) Auto-upload of latest sdcard-files files after every successful Jenkins build to two locations on the new filehost:

a) "**MEGA65 SD card essentials - No ROM**"
- https://files.mega65.org?id=0fb941fe-5c5f-4608-b0f1-32849d4a8dff
- Equates to file "**SD essentialsNoROM.rar**"
- Presently being done manually
- deft suggested that it also contains the latest OpenROM too
- so perhaps it could eventually be renamed to "**MEGA65 SD card essentials - OpenROM**"
- The latest OpenROM could be auto-downloaded within falk's automation from:
  - https://github.com/MEGA65/open-roms/raw/master/bin/mega65.rom

b) ""**MEGA65 SD card essentials**"
- https://files.mega65.org?id=a809e0ae-30ac-42f5-ab9c-766d72fd6331
- Equates to file "**SD essentials.rar**".
- Presently being done manually
- falk's automation might need to retrieve the latest closed-rom from the new filehost itself and add it into the .rar

# Manual Uploads
- Presently, the latest closed-rom and open-rom files are uploaded manually by adtbm and feralchild respectively
- Perhaps we're fine to keep this a manual step and no need to automate at this stage

**Comment by gurcei** [comment]
I'd better move my comments here about future automations needed into a separate ticket, so we can come back to it when the occasion comes to look into it.
