### ISSUE TITLE
Future automations needed to provide latest bitstream and fileset that docs can reference

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#177]
The ticket follows on from #172.

# Future automations needed

1) Auto-upload of latest .bit and .cor files after every successful Jenkins build (perhaps all zipped up into single file) to the new filehost

2) Auto-upload of latest sdcard-files files after every successful Jenkins build to two locations on the new filehost:

a) "**MEGA65 SD card essentials - No ROM**"
- https://files.mega65.org?id=0fb941fe-5c5f-4608-b0f1-32849d4a8dff
- Equates to file "**SD essentialsNoROM.rar**"
- Presently being done manually
- deft suggested that it also contains the latest OpenROM too
- so perhaps it could eventually be renamed to "**MEGA65 SD card essentials - OpenROM**"
- The latest OpenROM could be auto-downloaded within falk's automation from:
  - https://github.com/MEGA65/open-roms/raw/master/bin/mega65.rom

b) ""**MEGA65 SD card essentials**"
- https://files.mega65.org?id=a809e0ae-30ac-42f5-ab9c-766d72fd6331
- Equates to file "**SD essentials.rar**".
- Presently being done manually
- falk's automation might need to retrieve the latest closed-rom from the new filehost itself and add it into the .rar

# Manual Uploads
- Presently, the latest closed-rom and open-rom files are uploaded manually by adtbm and feralchild respectively
- Perhaps we're fine to keep this a manual step and no need to automate at this stage

**Comment by gurcei** [comment]
I know @Taygair and @frehwagen have already made efforts to automate various file uploads to the filehost.

So just as a reminder, I'll need to assess what they've got so far and see which url-links within our document need to be updated in relation to these new filehost locations (I.e., we'd like to remove those old scryptos links soon).

**Comment by Taygair** [comment]
Status of upload automation:
- Bitstreams: complete
- Manuals: in progress (manual_upload directory will disappear on the Filehost)
- CLI files and others: open

See the attachment of the static links of the manuals.

I have already informed Deft about adjusting the manual links on mega65.org
[book_links.txt](https://github.com/MEGA65/mega65-user-guide/files/7127665/book_links.txt)

**Comment by gurcei** [comment]
@Taygair - ok, sounds good. Though I think one thing that seems to be missing in your list is items 2)a and 2)b in my list. Are there any plans to automate upload of those two items to the filehost as well?

I ask due to there being steps in the manual that relate to these filesets, so I was hoping to transition such url's from the old scryptos to the new filehost too.

**Comment by Taygair** [comment]
@gurcei 

2a) does already exists on the Filehost (manually maintained atm by adtm but nevertheless the static link to it can already be taken over when it can/will be automated. So you can use the link for it in the book(s):  https://files.mega65.org?id=0fb941fe-5c5f-4608-b0f1-32849d4a8dff

2b) Same story like 2a) and link is also still valid: https://files.mega65.org/html/main.php?id=a809e0ae-30ac-42f5-ab9c-766d72fd6331 -> If used in books it also should be mentioned that only DevKit and MEGA65 owners have access to it due to Copyright reasons (otherwise note or howto patching the ROM -> BDF/RDF)

The upload script is there and working (even though it needs an adjustment for the Book uploads

**Comment by gurcei** [comment]
@Taygair 

Yep, the book already mentions those two links, and makes mention of the copyright matter too. Just my point of interest was in relation to the automation, but if that'll get sorted out later, no problem. Just as long as, whenever we do make the transition to get these automated, that they maintain the same url as is presently used in the docs (and don't change url link, let's say due to being uploaded via a different account).

As for the new bitstream links, ok, will update the docs with details on how to retrieve these from the filehost.

**Comment by Taygair** [comment]
@gurcei 

No, the links wont change, neither by manual upload nor by automatic upload. 
Falk mentioned a set of "stable" releases which may lead to a new set of files (and links) but that is not clear yet and not defined.

**Comment by gurcei** [comment]
Ok, feel like this ticket is sorted now, closing.

**Comment by gurcei** [comment]
Come to think of it, I'd better re-open this ticket, as some automations are still in progress (manual uploads) and some are yet to be addressed (2a and 2b, with the automated sdcard support file downloads).

So feel like it's better to keep this ticket open as a reminder to keep it on our radars.

**Comment by dansanderson** [comment]
The manuals are now uploaded to Filehost automatically by Jenkins. E.g. https://files.mega65.org?id=a5081244-a976-4a21-9153-27cca13fd613 (see the Published date).
