### ISSUE TITLE
Missing four closing brackets in file: configuring.tex

### ISSUE THREAD

**Issue by TheChief** [MEGA65/mega65-user-guide#178]
In the file: configuring.tex there are four closing backets missing.
Please have a look at this section:

...
This is how it works: When powering on, MEGA65 will search for- and boot these files:
\begin{itemize}
\item {\tt FREEZER.M65}
\item {\tt AUDIOMIX.M65}
\item {\tt C64THUMB.M65
\item {\tt C65THUMB.M65
\item {\tt MEGA65.ROM
\item {\tt MEGA65.D81 (default disk image, automatically mounted during start)
\end{itemize}
...

Attached a corrected version as .txt file due to missing .tex file type support.
[configuring.txt](https://github.com/MEGA65/mega65-user-guide/files/6736804/configuring.txt)

**Comment by gurcei** [comment]
I've added @TheChief 's changes into the repo, all sorted, thanks for sharing the fix :)
