### ISSUE TITLE
Add 'no lights when powering on' issue into troubleshooting section:

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#179]
@gardners requested we put this matter mentioned in the discord thread into the troubleshooting chapter:

https://discord.com/channels/719326990221574164/721846871357653004/858146224946413588

> gardners — 26/06/2021
> Meanwhile, I have been able to reproduce fairly reliably the "no lights when powering on" problem with the DevKits.  It is definately related to having certain HDMI devices plugged in while the MEGA65 is off, that don't provide enough power for the keyboard's CPLD to be properly powered on, but enough to stop it properly resetting when the MEGA65 powers on.  Removing the HDMI cable and turning the machine off and on again fixes it.
> @Gurce maybe we need a brief paragraph on this in the troubleshooting chapter of the userguide, if you are willing to add it while you have the bonnet open on the manual?

**Comment by Edilbert** [comment]
Yes, go ahead please.

**Comment by gurcei** [comment]
Have added this, and also tidied the troubleshooting output up a little bit too
