### ISSUE TITLE
Example Programs and Element Catalogue

### ISSUE THREAD

**Issue by mds75** [MEGA65/mega65-user-guide#18]
I assume that the "Element Catalogue" at the back of the User Guide is for some additional example programs that don't fit elsewhere in the book. Could someone please confirm this?

I can contribute some example programs to this section. Should they be C65-compatible BASIC 10 programs or MEGA BASIC programs or either BASIC 10 or MEGA BASIC?
 
I've written a couple of graphics routines that work in BASIC 10 despite the fact that there are some C65 BASIC 10 statements that are missing some functionality.

**Comment by sausagejohnson** [comment]
The element catalogue is just a scratch pad for testing the components like the sprite grid etc. 

It can be removed.

**Comment by mds75** [comment]
Okay thanks for the clarification about the Element Catalogue. :)

One thing that I'm still a bit confused on is whether all example programs that I write should be written in MEGA BASIC or BASIC 10 (I've written them in BASIC 10 so far, to be used on the C65. I noticed that Appendix B is a BASIC 10 Command Reference so I assume that BASIC 10 is the target language for now)

**Comment by gardners** [comment]
More specifically: The element catalogue is there for us to reference, until each element has been used at least once somewhere in the manual, just to make it easier for us to work out how to do particular things.

**Comment by sausagejohnson** [comment]
As @gardners said, so we could keep it around for testing newer components that aren't yet used. Sprite Grid is used as is the code listing and button wrappers, so they could go. That's why it's tucked at the end.

While I usually test components in their own space, I still need to test them in the main document to check for LaTeX weirdness.

**Comment by sausagejohnson** [comment]
I'll change this issue so that the catalogue can be broken out.
