### ISSUE TITLE
part / chapter / appendix sectioning is a little confusing

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#180]
# TOC gripes

The toc looks a little odd at present:

<img src="http://gurce.net/mega65_logs/images/img_2021_07_02_6_20_19.png" width="50%"/>

I'm seeing:
- CHAPTER 1 - Introduction
- PART 1 - GETTING TO KNOW YOUR MEGA65
  - CHAPTER 2 - SETUP

I.e., 'CHAPTER 1', followed by "PART I" looks a bit funny to my eyes (two 1's in a row)
- I'm feeling perhaps there should be an earlier part to contain the "CH1 - Introduction", perhaps a "PART I - PREFACE" or "PART I - FOREWORD"
- To make this distinction between a PART and a CHAPTER easier on the eyes, perhaps we could indent chapters a little bit to the right of their PART parents.

# Gripes with Chapter 1 in TOC

for "CHAPTER 1", the sole subsection of "Other Books in this series" seems a little bit lonely and odd to me.
- On first glance, it gives the impression of "Let me welcome you to this book by introducing you to other books!"
- I'd suggest an initial subsection of "Welcome to the MEGA65!" (then followed by the existing "Other Books in this series")

# To Capitalise titles or not

- The titles for "CHAPTER 2 - SETUP", "CHAPTER 3 - GETTING STARTED" and "APPENDIX A - ACCESSORIES" are in upper-case, while all other chapters are in mixed case.
- I'm feeling like the majority of the book is following a convention of PART titles in capitals, and CHAPTER titles in mixed case, so Ch1 and Ch2, and AppendixA should follow suit

# Weird Appendix numbering

The Appendix numbering is confusing, starting with:

- APPENDIX A - ACCESSORIES
- APPENDIX B - BASIC 65 Command Reference
- CHAPTER 3 - Special Keyboard Controls and Sequences
     
So they started with alphabetic characters, but then later switched to numbers. This makes for a confusing state of the book having two CHAPTER 3's and two CHAPTER 4's, and so on.

@gardners made a mention of this appendix/chapter matter in a comment on another ticket:

- https://github.com/MEGA65/mega65-user-guide/issues/136#issuecomment-756543814

His suggestion there was for all sections in the Appendix to be given alphabet characters. Should we go ahead and do that then?

**Comment by Edilbert** [comment]
You're right. This manual was set up as a subset from the huge book, so some organisation looks odd now.
If you take the task to harmonize the layout and remove the confusion, I'd be happy.
I'll also contribute to the layout improvement, but am currently still working on ROM bug fixes and BASIC description issues.

**Comment by gurcei** [comment]
Sorted these out now. Seems like @Edilbert already sorted out the matter about appendix chapters using alphabet letters, that's already looking fine now.
