### ISSUE TITLE
A few missing international characters in MegaGlacial-Regular font

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#181]
The latex build output makes mention of a few missing international characters in our MegaGlacial-Regular font. As some of these missing characters relate to special characters in donors' names, feel like we'd better repair these, as a courtesy to those that donated to the mega65 cause, and assure we get their names printed correctly in the document.

```
Missing character: There is no ł in font [fonts/MegaGlacial-Regular.otf]/OT:scr
Missing character: There is no Ś in font [fonts/MegaGlacial-Regular.otf]/OT:scr
Missing character: There is no Ş in font [fonts/MegaGlacial-Regular.otf]/OT:scr
```

There is also ISBN/nullfont issues, but that might be another matter (a missing font on the travis build agent perhaps?)

```
Missing character: There is no I in font nullfont!
Missing character: There is no S in font nullfont!
Missing character: There is no B in font nullfont!
Missing character: There is no N in font nullfont!
Missing character: There is no 1 in font nullfont!
Missing character: There is no 2 in font nullfont!
Missing character: There is no 3 in font nullfont!
Missing character: There is no - in font nullfont!
Missing character: There is no 4 in font nullfont!
Missing character: There is no 5 in font nullfont!
Missing character: There is no - in font nullfont!
Missing character: There is no 6 in font nullfont!
Missing character: There is no 7 in font nullfont!
Missing character: There is no 8 in font nullfont!
Missing character: There is no 9 in font nullfont!
Missing character: There is no 0 in font nullfont!
Missing character: There is no - in font nullfont!
Missing character: There is no 1 in font nullfont!
Missing character: There is no 2 in font nullfont!
Missing character: There is no - in font nullfont!
Missing character: There is no 8 in font nullfont!
```

**Comment by gurcei** [comment]
I noticed that older mega65-book.pdf files showed the ISBN like this:

![correct_isbn](http://gurce.net/mega65_logs/images/img_2021_07_04_1_34_07.png)

Newer mega65-book.pdf generated by travis are missing the line of text at the top (I suspect this is the 'nullfont' issue:

![incorrect_isbn](http://gurce.net/mega65_logs/images/img_2021_07_04_1_35_11.png)

**Comment by gardners** [comment]
A guide on easily creating accented chars using fontforge:
http://designwithfontforge.com/en-US/Diacritics_and_Accents.html
This was able to auto-create 2 of the three chars. I had to manually create the lslash.

**Comment by Edilbert** [comment]
Very well! Do you update the font file in the repository?

**Comment by gardners** [comment]
Yes. It builds for me now, and looks fine, but I am not really sure how those characters should look. In particular, maybe the lslash is a bit too tall, I don't know.

**Comment by Edilbert** [comment]
OK, I restore the donor's table to use these special characters again

**Comment by Edilbert** [comment]
Oh, I see, you did it already.
I built it too and indeed the slash L looks different, but I think, it's OK.

**Comment by gardners** [comment]
Yes, I think it might be too tall, but I just copied the normal L, so I don't know why.  But I agree that I think it gets us an acceptable solution, and better than leaving the accents off.  Someone who is a font guru can improve it when they get inspired/aggrovated by it ;)

**Comment by gurcei** [comment]
As mentioned in this discord thread:
- https://discord.com/channels/719326990221574164/720355877701550131/865216191580471306

> Taking a look at some other names, it seems like certain characters like 'l', 'b', 'k' and 'h' are always slightly taller:
> 
> So seems like the nature/design of the font to be that way.

Given that, I'm fine with the way these names look now.

So the only remaining matter for this ticket is this 'nullfont' thing on the ISBN

**Comment by gurcei** [comment]
I'll sort out those missing fonts mentioned in the missfont.log file now.

Looks like I just need to install a few more packages:
- zapfding (contains pzdr.tfm)
- helvetic (contains phvr7tn.tfm)

**Comment by gurcei** [comment]
Yep, ISBN looks fine now, closing the ticket
