### ISSUE TITLE
Move automated docs to mega65.org

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#185]
Presently, they've been temporarily hosted at gurce.net/mega65_files/docs

I'll been given access to move the automated-upload of these docs to mega65.org, just need a free moment to make it so.

NOTE: Once done, the mega65.org website will need its menubar updated so that its "DOCS >> MEGA65 USER'S GUIDE (WIP)" option links to the new url for the docs.

**Comment by gurcei** [comment]
Ok, this has been sorted out now. Docs are now being uploaded to:

- https://files.mega65.org/manuals-upload/

**Comment by mkdj69** [comment]
Hello Gurcei
I think the automation to https://files.mega65.org/manuals-upload/ is broken - seems to have stopped after the 22.07.2021 ...
Markus.

**Comment by gurcei** [comment]
Thanks for the heads-up! I've taken a look on the travis build-automation side, and it looks like we have exhausted our free credits, and we'll need to ping the travis folks to ask for more. I've brought it up in this Discord thread:
- https://discord.com/channels/719326990221574164/720355877701550131/873871904900014130

**Comment by mkdj69** [comment]
Hi Gurcei
It's working and up to date - tested just now!
Thank you kindly,
Markus.

**Comment by gurcei** [comment]
No probs :) There still seems to be some probs to sort out with the missing title-page and toc, but can dig into that stuff on the next opportunity. Good to have the automated builds back :)

**Comment by mkdj69** [comment]
Just pulled down the automated editions of 11.08.2021 "add section keywords and tokens" and it seems to be ok - will go through the others too - but i think the title page and table of contents is fixed.

**Comment by gurcei** [comment]
Relieved to hear it :)
