### ISSUE TITLE
Wording at page xv

### ISSUE THREAD

**Issue by Impakt** [MEGA65/mega65-user-guide#187]
Page `xv`

> Excitement for the MEGA65 will grow as we discover  what programmers as they learn about the power and features of this  modern Commodore computer recreation. 

Perhaps it should be

> Excitement for the MEGA65 will grow as we discover what programmers **can do** as they learn about the power and features of this modern Commodore computer re-creation. 

Note the hyphen for `re-creation`

Page `xvi`
> The MEGA65 Chipset Reference – Detailed documentation about the MEGA65 and C65’s custom chips

The MEGA65 Chipset Reference – Detailed documentation about the MEGA65 and **the** C65’s custom chips

I'm happy to create a PR if you find this small edit worthy.

**Comment by gardners** [comment]
Would you like to make a pull request for these changes? Yes, these sorts of changes are great to get in.

**Comment by Impakt** [comment]
I'll suggest my changes in PRs
