### ISSUE TITLE
Do I need to be added as a maintainer?

### ISSUE THREAD

**Issue by mds75** [MEGA65/mega65-user-guide#19]
Hi,

I'm getting a permission denied error whenever I try to push my files into the repository.

I'm using the command 
git push origin master

but I get back error 403.

I have about 35 pages I would like to upload for Decimal, Binary and Hexadecimal conversion, plus some Reference Tables.

Does someone need to add me as a maintainer of the repository first? Or is it a problem at my end?

Thanks for the help.

Mark

**Comment by sausagejohnson** [comment]
Hi Mark, might be better to push to your fork and do a PR?

**Comment by gardners** [comment]
Hello,

Fork the repository, then commit to your fork, and then create a
pull-request. We can then review the pull-request and slurp it in.

Super excited to see what you have done!

Paul.

**Comment by mds75** [comment]
I think I've worked it out :). Thanks.
