### ISSUE TITLE
Screen editor screen shot out of sync with the description

### ISSUE THREAD

**Issue by Impakt** [MEGA65/mega65-user-guide#193]
The first screenshot in the screen editor section mentioned the additional hardware as `peripherals`, but the text mentions additional `hardware`. Would be nice to keep them in sync. I can change the text to peripheral, or we can update the screenshot. Any preference? Or just leave it?

**Comment by gurcei** [comment]
For me, I'm 50-50 on it, as I don't mind either term. Perhaps the text could say "hardware peripherals" if you wanted to strengthen the connection to the diagram above it?

**Comment by Edilbert** [comment]
All screenshots showing the old 91xxxx ROM and the C65 start messages,
shall be replaced by new ones with the MEGA65 start screen and the newest 92xxxx ROM.
