### ISSUE TITLE
Remarks for the hardcopy MEGA65 User Manual

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#201]
1. On the back cover, add some notes about the M.E.G.A. project, aim, history

[SKIP?] Think we've got a list of authors/contributors at present, but it's a nice idea to have a home for such a story somewhere :))

2. Add the ‘Getting started in BASIC’ chapter of the online manual into the User Guide

[SKIP] - As per @Edilbert 's response, 'ADD' actions for the User guide are limited

3. In the ‘Getting started in BASIC’ section, add instructions on how to format, read, write, list, dir. Do this for both SD and real floppy, in C64 and C65 mode. Also explain what a D81 image is (represents a physical disk, same capacity, needs to be ‘mounted’, etc)

[SKIP/SEMI-DONE] - It's a big add, but worthy content that deserves a home somewhere one day. Hopefully the recent documenting of the freezer and accessing d81 images goes some way in helping in this area.

4. Add the ‘Text Processing’ chapter of the online manual

[SKIP?] - not familiar with this one right now, but I'll guess that big 'adds' are out.

5. Put ‘Cores and Flashing’ into an appendix (leave it in the manual as it is an important part of the MEGA65 capabilities). Describe the overall behaviour (how computer boot slot 1 or slot 0, do not mess with slot 0, etc) and general instruction how to add a core. Take out all the specific links and detailed instructions. Do that in the MEGA.org page or somewhere else online.

[SKIP?] While I was on your wavelength with the idea of making this chapter less prominent, I feel that the big players in the project do want to promote the core/flashable nature of this project as an asset, so I understand why they'd want it kept in a more prominent position. Fair enough.

6. In an appendix, add general instructions on how to add .prg files to D81 image via another computer or network. Detail instructions can be done online

[SKIP?] I agree this would be super-useful stuff, but too big an 'add' right now.

7. Remove ‘BASIC65 Condensed Reference’ (but provide the full version separate, and the ‘Getting started in BASIC’ chapter)

[SKIP] BASIC 65 Reference is staying, I wish we had rroom for a 'getting started' too, but sadly no

8. Maybe nice to add ‘Supporters’ as an appendix

[DONE]

9. Add some basic instructions how to use GEOS

[SKIP] Too big an 'Add' right now.

10. Replace all references to online sites with a more generic one (that also will still work after a decade)

[SEMI-DONE] We recently added several redirects here and there (such as https://mega65.org/chat , https://mega65.org/forum , https://mega65.org/mega65-book , etc) and made mention of them within the manual.

11. Add a ‘Quick reference card’ at the inside of the back cover (ala C64 User Manual). Add the instructions how to switch to/from C64/C65 mode and add instructions how to change speed (1MHz, 3,5MHz, 40MHz). Also add the available shortcuts for BASIC65 (/ for loading a file, etc)

[SEMI-DONE] A nice colourful reference card got added recently of categorised BASIC commands.

12. Add instructions how to switch ROM’s, I believe that will be possible with the Freeze menu?

[SKIP] I don't think we covered this, and maybe it's for the best, as that mechanism is still a work-in-progress.

13. Add instructions in an appendix how to install “firmware” updates (Core / ROM), maybe needed to install patches and bug fixes

[SKIP] They're good things to document, but I hope for some of the areas we've been lacking like this, folks will take our invitation to join in forum64.de posts and discord chatter and ask any q's on missing gaps in their understanding. I also hope some gaps might get documented in filehost articles / wiki pages in time too.

14. Add a chapter about PASCAL, C or other higher level programming languages with links to KickC etc

[SKIP] I think the MEGA65 Book touches on some of this, and happy to leave it there.

15. Maybe some notes about how to program in asm and/or links to good reading material? Also add the MONITOR documentation

[SKIP] In BASIC 65's `MONITOR` description, they suggest `More info on the MONITOR is available in the MEGA65 Book`, I'm fine with that.

16. Maybe I missed it somehow, but some info about how to use the IEC bus is also good. Including drive numbering etc

[SEMI-DONE] I recall impakt recently added some info into the freezer chapter, maybe that helps in this area a little?

17. Add how to use ‘autoboot.c65’

[DONE] We recently added an example into the freezer chapter.

18. Add how to use the cartridge port and some notes about how C64 mode is detected

[SKIP] too much 'add' for user manual, but hope such details make their way into other locations.

19. In C64 mode, are there some POKE/PEEK addresses what we know on forehand will not work? If yes, maybe good to mention them

[SKIP] Ah, it feels like a big topic and probably too big an 'add' (even investigating it might take a while)

20. Add some info about the newly added graphical modes (what’s new wrt C64)

[SKIP] It's a good topic, I noticed M3wP had started a tutorial pdf at one stage, and I hope more 'walkthrough' style writing of the graphics modes will surface in time, but probably can't make it into the user manual right now.

21. Add a “Sound and Music” chapter with explanation how to use the new SID’s.

[SKIP] Big add content which won't make it into user guide, but I hope we find a home for them in other/bigger books.

22. Add an appendix with spec sheet MEGA65 vs C65

[SKIP] Don't think I'll be able to chase all the details for a comparison in time for print.

**Comment by Edilbert** [comment]
There was a team discussion, what should be included in the print manual.
The main restriction is, that the manual should have 240 pages (or a few more if absolutely necessary).
So most of the "ADD requests" cannot be done due to the page limit.
There will be more manuals/guides/references in the future, but this one has to be compact.
The deadline is approaching and we have to focus on eliminating typos and errors and improving the layout.

**Comment by MauriceMEGA65** [comment]
Thank you for the update Edilbert!

My personal preference would be to supply 2 manuals; a User Manual with all the above ingredients, and a separate full blown BASIC65 manual.
It will increase the cost maybe with ~20 euro per MEGA65.

I do understand however the reasoning for 1 printed manual. I'm sure the end result will be fabulous anyhow!

**Comment by gurcei** [comment]
Looking back on this list, while we didn't cover everything here, but there were a few items here that we've sorted out :)

**Comment by MauriceMEGA65** [comment]
I’m happy to close it if the open items are aborted. Not sure if anyone is still looking at those…

**Comment by gurcei** [comment]
Maybe I can try edit your initial post and add 'DONE' or 'SKIP' prefices to anything I'm aware of.

**Comment by MauriceMEGA65** [comment]
User Guide is closed / being printed. This comment can be closed
