### ISSUE TITLE
Add a foreword from the MEGA team

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-user-guide#202]
I just read a little bit in the manual of the Spectrum Next. It could be download here: 

https://www.specnext.com/zx-spectrum-next-user-manual-first-edition/

A nice idea was besides a decication to the late designer Rick Dickinson it has a 5 page long foreword from the developers about the long way from the idea to the ready build Spectrum Next with background infos. 

Maybe a few words in a foreword from the team would also be an idea for the printed MEGA65 manual? To the MEGA65 also belongs the year long way to his end production. ;-)

**Comment by dansanderson** [comment]
Resolving this to clean up some old issues. We'll consider a foreword as we edit our raw text into proper books. Front matter is appropriate. The User's Guide has a two-page Welcome that suffices for now.

(Oddly, the SpecNext manual 3rd ed. has no foreword, and even locates their table of contents to the back. It just jumps into chapter 1. 😅)
