### ISSUE TITLE
LIST P not in manual + LIST p gives a cosmetic issue

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#203]
1. Please add the BASIC instruction LIST P to the manual
2. While executing LIST P, some letters of [MORE] are visible in the listing.

![Screenshot 2021-08-25 at 22 28 21](https://user-images.githubusercontent.com/75681098/130860019-77dd502a-4834-4743-9e1b-e7b24008c250.jpg)

**Comment by Edilbert** [comment]
The [MORE] prompt will now be erased before the next page is printed.
The LIST [P] is documented.
