### ISSUE TITLE
BASIC example CHR$, line 40 redundant?

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#206]
Not sure I understand the function of line 40, especially the PRINT "Q".
With or without line 40, I do get exactly the same results (at first glance).

**Comment by gurcei** [comment]
Hehe, I'll admit it's a pretty cryptic example :)

It is making use of an escape shortcut key sequence, you can perform the same shortcut manually to get a better idea of it.

Let's say you have a long line of text and you position your cursor in the middle of it:
![image](https://user-images.githubusercontent.com/20013309/132118307-1514fd0a-cded-41a8-9af7-e5b68212e955.png)

Pressing ESC then Q will delete all the characters that follow your cursor on this line:
![image](https://user-images.githubusercontent.com/20013309/132118338-4cf7a857-9117-472c-86a2-f201e509781a.png)

Another shortcut similar to it is ESC then P, which will delete all the characters preceding the cursor on that line:
![image](https://user-images.githubusercontent.com/20013309/132118374-13eca62c-4670-4b62-afdf-fe743a4f5140.png)

So in the context of this example, it assures that whatever line follows on from the "MEGA65" output will be wiped.

E.g., if you were to run the program slightly above the listing of the program:
![image](https://user-images.githubusercontent.com/20013309/132118410-05bc1a09-d763-483b-bd7a-52296641908e.png)

...then then notice the line below "MEGA65" gets wiped:
![image](https://user-images.githubusercontent.com/20013309/132118433-a8ef1325-0817-4b71-b8e9-6a6e436a00ab.png)

So I'll leave this example be, it's pretty cryptic I admit, but hopefully curious folks will either ask about it or figure it out over time :)

**Comment by MauriceMEGA65** [comment]
Aha, thanks for the explanation!!
