### ISSUE TITLE
BASIC example CLR, unable to get same results as in screenshot

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#208]
The very last line in the example shows "00,OK,00,00"
How to get these results?

Another thing: running the example gives me an " 0", meaning there is an indent. Maybe it's a minor thing, but I cannot explain it and is different than is in the manual.

**Comment by gurcei** [comment]
Ok, I tested this, it seems our newer roms no longer output the `DS$` string, while the original 911001.BIN rom does. Will put it on @Edilbert 's radar.

**Comment by Edilbert** [comment]
I had to change the DS and DS$ handling.
In the 91xxxx version DS and DS$ sometimes were read from the disk drive, sometimes they came from cache and sometimes they were printed, but came from the wrong unit. It was somehow unpredictable.

My implementation, which needs to be updated inthe manual:
Only the usage of DS triggers the reading of the error channel from the currently active unit.
It updates both DS and DS$ and any error condition on the drive is cleared by this reading.
So a typical usage should look like this:
100 IF DS THEN PRINT DS$
or
D8=DS:D8$=DS$:REM GET AND SAVE THE DISK STATUS

**Comment by Edilbert** [comment]
manual updated.
