### ISSUE TITLE
BASIC examples EL and ER loops in line 120 error

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#216]
Output loops in "can't resume error in line 120"
This is probably as expected, but I would like to have a "closed" BASIC example to make sure the user understand that this is an expected result and not a typo on his/her side.

Same for the ER example.
I think one and the same example can be used for both EL and ER.

**Comment by Edilbert** [comment]
RESUME doesn't work correctly. This bug is in there since the C65 ROMs, I tested it with the 911210 ROM.
I have to fix that. Thanks for the report.
