### ISSUE TITLE
BASIC example LOADIFF, remove instruction on how to convert on Linux

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#225]
I think the link on how to convert JPG to TIFF does not belong in the BASIC manual and should be removed.
I rather have one or two TIFF examples on the D81 image to make the LOADIFF example work.

**Comment by Edilbert** [comment]
Yes, it's not part of the BASIC manual, but for the reader the first question will be:
"How can I create an IFF" image or convert an existig image, suitable for the MEGA65.
This hint does not extend the size of the manual and may save some readers hours of research.
Therefore I opt for keeping that remark.

**Comment by MauriceMEGA65** [comment]
ok
