### ISSUE TITLE
BASIC example LOG, add LOG2 and combine LOG+LOG2+LOG10 on 1 page

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#226]
As mentioned in the subject:
1. Please add LOG2
2. Combine instructions for LOG(e), LOG2 and LOG10 all in one page

**Comment by Edilbert** [comment]
I'm not sure, whether LOG2 would be really useful.
Even scientific pocket calculators have only LN and LOG10.
And combining LOG/LOG10 would violate the concept 1 page for 1 command.
Then it would be necessary to combine SIN/COS or PRINT/PRINT# too.
So I'd prefer to keep the descriptions separate, as they are.

**Comment by MauriceMEGA65** [comment]
ok
