### ISSUE TITLE
BASIC example RECORD, shows a list of Pi(?)

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#234]
![Screenshot 2021-08-30 at 19 41 19](https://user-images.githubusercontent.com/75681098/131381554-cafaf93a-94a9-4e18-81e5-ce8b522eb3f8.jpg)

**Comment by Edilbert** [comment]
This example works only, if the two files "DATA INDEX" and "DATA BASE" exist
and are properly filled with data. 
I'll write a new example, which does not depend on existing files"

**Comment by Edilbert** [comment]
New example written and tested
