### ISSUE TITLE
BASIC example SCREEN, unclear symbol in text used

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#238]
![Screenshot 2021-08-30 at 22 20 25](https://user-images.githubusercontent.com/75681098/131400240-9bbe2231-40fe-48f3-9297-e62bc4e28f2a.jpg)
Not sure what is ment with the up-arrow, see screenshot

**Comment by Edilbert** [comment]
replaced with exponential operator ^
