### ISSUE TITLE
BASIC example SPC, update screenshot

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#239]
Please update according to the attached screenshot. That is, if the zero's are expected.
![Screenshot 2021-08-30 at 22 35 52](https://user-images.githubusercontent.com/75681098/131402054-bf3d2ab0-28b1-47f6-bd00-d4144718522e.jpg)

**Comment by Edilbert** [comment]
There is a typo in your example in line 20:
It should be SPC not SPS.
