### ISSUE TITLE
BASIC example TI$, seconds missing?

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#242]
Example program (under Remarks) does not seem to show seconds. Please verify

**Comment by Edilbert** [comment]
10 FORI=0TO5:T(I)=PEEK($FFD7110+I):NEXT
20 FORI=2 TO 0 STEP -1:PRINT HEX$(T(I));" ";:NEXT

RUN
0091 0051 0005

I cannot reproduce the issue.

**Comment by Edilbert** [comment]
Typo
