### ISSUE TITLE
mega65-basic65-reference.pdf ( old mega65-basic10-reference.pdf ) not being auto generated

### ISSUE THREAD

**Issue by mkdj69** [MEGA65/mega65-user-guide#251]
mega65-basic65-reference.pdf not being auto generated for accessibility from "https://files.mega65.org/manuals-upload/" since the naming changes implemented on approx.  01/09/2021 ...

**Comment by gurcei** [comment]
Thanks for pointing this out, I've pushed a fix now, so hopefully this pdf file will re-appear in about 5 minutes.

**Comment by mkdj69** [comment]
Thanks as always Gurcei!  Excellent work :)
