### ISSUE TITLE
Same title on every build book

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-user-guide#253]
I've seen that all 5 generated books have the same title on the first (cover) page called "User's Guide". Each book should have it's own title on the cover:
- User's Guide
- Chipset Reference
- BASIC 65 Reference
- Developer's Guide
- Book (Complete Book?)

**Comment by gurcei** [comment]
Ok, have made some placeholder title pages for all the other books (as will as a gimp 2.10 .xcf file, for anyone that wants to dabble with other ideas).

But I still need to figure out some latex magic to decide on which title-graphic to use based on the book currently being built.

**Comment by gurcei** [comment]
Ok, latex magic is sorted. We've also settled for changing the formal/print-name of 'The MEGA65 Book' to be 'The MEGA65 Complete Compendium', to still making mention in the documentation that the document is 'also known as' 'The MEGA65 Book'.

Ok, think we're sorted on this card now, so will close.
