### ISSUE TITLE
SCREEN function result in light blue border.

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#254]
Whenever I use the 'shortened' SCREEN function (without SCREEN DEF) and I do not first set a BORDER color, I get this light blue border.
Seems only to occur when screen depth is 2.

See CHAR and SCREEN1 examples.

![SCREEN1](https://user-images.githubusercontent.com/75681098/132494901-955a36fe-8032-41aa-8d7b-859026c77460.jpg)
![CHAR](https://user-images.githubusercontent.com/75681098/132494906-0d6c15ff-5f0d-4e60-bb34-fb4c0e1b694e.jpg)

**Comment by Edilbert** [comment]
Further investigations show, that this is probably a VIC issue, that should be solved in the core.

**Comment by MauriceMEGA65** [comment]
https://github.com/MEGA65/mega65-core/issues/441
