### ISSUE TITLE
Should chapter 2 also provide a diagram of the trap-door?

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#289]
"Chapter 2 - Setup" already provides diagrams for 'rear connections' and 'side connections'.

So I wonder, for the sake of completeness, should we also provide a 'trap-door connections' diagram too?

**Comment by Edilbert** [comment]
I think, this is not so important for the User's Guide, but maybe added later for the complete book.

**Comment by gurcei** [comment]
Fair enough. Perhaps then could we just make brief mention of the trapdoor and its SD card and 2 x PMOD connectors in the 'Optional Connections' section?

Oh, also, in the 'Rear Connections' diagram, wondering if we should rename item 2 to read as "2. External microSD Card".

My train of thought with this is: in a later chapter on configuring, mention will be made of there being external and internal SD card connectors, and of there being a trapdoor, and they maybe revisit this chapter to clarify what is meant by such terms. I.e. they may not even know what is meant by 'trapdoor' or where it is located, so perhaps if we just expressed it briefly in words here, that'd be enough.

**Comment by Edilbert** [comment]
I agree.
