### ISSUE TITLE
(configuring.tex) Links to SDCARD files with ROM and without ROM - broken on website.

### ISSUE THREAD

**Issue by mindrail** [MEGA65/mega65-user-guide#290]
. I'm not sure if this is something that should be updated on the website to match the manual, or changed in the manual (I think perhaps updated on the website).. so I'm guessing @Tayger  .. On page 29 of the User guide.. 
The section under SUPPORT FILES.. the link to http://mega65.org/sdcard-files and http://mega65.org/sdcard-norom both dont work on the website anymore. I was about to change the links in the manual, but I think it makes more sense to fix them on the website side.

**Comment by mindrail** [comment]
Gurce — Today at 7:14 PM
Yep, these are new aliases that will need to be added to the mega65.org server. I've pinged @deft on this so he can update at his next free moment.

**Comment by gurcei** [comment]
@deftmega has updated the aliases, they're all working now :)
