### ISSUE TITLE
Should BSAVE description make mention of its two modes (Flat addressing + Bank addressing?)

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#294]
I noticed that the `BLOAD` command's description got updated with details on its new flat addressing capabilities. I'm wondering if `BSAVE` command's description either needs to be updated to something similar or reader could be referred to `BLOAD` for more details?

**Comment by Edilbert** [comment]
You're right, BSAVE needs an update with the flat memory mode.
I'll do that.
