### ISSUE TITLE
Userguide Preface - Missing online link

### ISSUE THREAD

**Issue by snoopy-f64** [MEGA65/mega65-user-guide#302]
In the preface of the user guide at page xxi at the bottom the online link is missing. The text stops with "Get involved, learn more about your MEGA65, and join us online at:", then a new page with the mention of the other books follows.

**Comment by Impakt** [comment]
There's a TODO in the source to populate this, which will be addressed before it goes to print.

**Comment by snoopy-f64** [comment]
So where should I put the hints to typos and so?

**Comment by Impakt** [comment]
The best way is to create a pull request with your suggested fixes. Alternatively you can create another issue, or get in touch with us on [Discord](https://discord.com/channels/719326990221574164/)
