### ISSUE TITLE
ST codes

### ISSUE THREAD

**Issue by jimnicholls** [MEGA65/mega65-user-guide#307]
For the ST system variable, the manual stops with:

> … it is set to a device dependent error code.

and we look up the device manuals for these codes. 

For CBDOS this is the device manual. It would be good to see the ST codes for CBDOS here.

**Comment by jimnicholls** [comment]
I've confused ST with DS, haven't I?

**Comment by Edilbert** [comment]
ST was mostly used for RS232 (modem) or tape devices, which are both not supported by the MEGA65.
The only remaining usable function is, that ST is set to 64, if the last byte of the file is read.
