### ISSUE TITLE
COPY

### ISSUE THREAD

**Issue by jimnicholls** [MEGA65/mega65-user-guide#308]
The manual says this for COPY

> If the source unit (before TO) is different to the target unit (after TO), COPY is executed in MEGA65 BASIC by reading the source files into a RAM buffer and writing to the target unit. In this case, the target file name cannot be chosen, it will be the same as the destination filename.

What does this last sentence mean? This is first reference to "destination filename".

**Comment by jimnicholls** [comment]
I just noticed from the examples, perhaps that is meant to be "source filename".

Also from the examples the syntax template is wrong because target is optional — if not outright forbidden — for unit-to-unit copies.

**Comment by Edilbert** [comment]
Tnak you
