### ISSUE TITLE
SD Card Bus #'s in Text Don't Match Screenshot

### ISSUE THREAD

**Issue by IvanRII** [MEGA65/mega65-user-guide#317]
On page 24, on the paragraph that starts, “Select the number…”, the second-to-last sentence reads, “The external SD card is bus 0, and the internal card is bus 1.”  On the top of page 25, the screenshot says on line 2, “SD Card 0 (Internal SD slot):” and on line 13, “SD Card 1 (External microSD slot):”.  The paragraph on page 24 and the screenshot on page 25 talking about the SD Card bus slots don’t match.

From IvanRII on Github (IvanR2 on Discord).

**Comment by gurcei** [comment]
Aah thanks for spotting this, I recall updating the screenshot recently based on it being an old screenshot and there was feedback on ticket #93 that there was a mix-up between the internal/external sd-cards already in relation to wording that appeared later on this page.

So looks like the screenshot was updated to suit that wording, but we overlooked this earlier wording, updating it now, thanks for spotting it :)

**Comment by IvanRII** [comment]
Gurce,

You are very welcome!!  Glad I could help!!  Looking forward to receiving my MEGA65 when they ship (I was fortunate enough to be in the first 400 group — Order # 37528).

Best Regards,

Ivan Richardson II
***@***.***
IvanR2 on Discord
IvanRII on Github
