### ISSUE TITLE
Diagram of the MAP instruction and register usage

### ISSUE THREAD

**Issue by john-098** [MEGA65/mega65-user-guide#320]
On page G-9 where the usage of the registers a,x,y,z are discussed, there is a mixture of registers and pseudo hex-numbers, e.g. LDX #$ZD. This Nibble with the value "Z" is apparently used to illustrate which 8kb block is modified (column "Offset Enable?") but there bit indices > 3 are used. Nibbles only consist of 4 bits, so I guess the Column "Offset Enable?" erroneously lists the pseudo-value of said nibble where the name of the register which affects whether an 8kb block is modified should instead be printed.

**Comment by dansanderson** [comment]
I agree that the offset enable column is confusing in how it refers to the nibble but gives the register bit offset. It's not technically incorrect (if you imagine the nibble's place in the byte), and the bit number is important. Given the concision of the diagram, I'm not inclined to change it.

The good news is there's a new chapter on memory with a tutorial-style description of MAP that complements the reference appendix. Hopefully that helps to clarify. I'll take another pass at the appendix now that the tutorial chapter is in place to see what else can be cleared up.
