### ISSUE TITLE
Consider HK Grotesk for the main font. Experiment and submit to group for opinion

### ISSUE THREAD

**Issue by sausagejohnson** [MEGA65/mega65-user-guide#33]
AO:

Typography: Fonts typically have to be licensed for publishing. I noticed that one of the main fonts is by Hanken Design Co. They have a font called HK Grotesk which is completely free and would make a good substitute. https://hanken.co/hk-grotesk/ For code snippets, Source Code Pro is a good choice: https://github.com/adobe-fonts/source-code-pro

**Comment by Edilbert** [comment]
In a separate discussion we agreed to stay with a modified version of the free font "Glacial-Indifference" from Hanken. Our modifications includes adding the glyph for the pound sign and making all digits equal width. So I think, we can close this issue now.
