### ISSUE TITLE
On-Boarding chapter: Press RETURN while close the setup screen?

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#332]
Page 30 confuses me. Is pressing RETURN needed between each step, or will pressing RETURN result in closing the setup screen?

![IMG_0430](https://user-images.githubusercontent.com/75681098/137200788-e8a72494-babe-4f9a-83dd-10ae50e22958.jpeg)

**Comment by gurcei** [comment]
Ok, I've improved the wording on the onboarding screen to the following:
![image](https://user-images.githubusercontent.com/20013309/139674690-e5de0521-b592-4907-af63-37dde6689a25.png)

I've made new screenshots for the manual, but they'll need a few purple annotations on them, which I've pinged impakt on.

**Comment by gurcei** [comment]
Ok, impakt has updated the screenshots in this PR:
- https://github.com/MEGA65/mega65-user-guide/pull/411

So we're all good now :)
