### ISSUE TITLE
The Freezer chapter: unclarity about 'drive 0' and 'drive 1'

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#334]
I needed multiple reads to get this clear for myself, but still I have questions:

1:
Why is the text **DRIVE 0** bold? I would expect only **UNIT** to be bold

2:
_drive 0/1_ after the text UNIT, DRIVE, is that the same _drive_ as mentioned after the toggle commands?
If yes, please use an * or different font

![Screenshot 2021-10-13 at 21 54 49](https://user-images.githubusercontent.com/75681098/137205848-357338a4-26f4-492c-af8f-967914a0eddb.jpg)

**Comment by MauriceMEGA65** [comment]
Perhaps not 100% accurate, but I believe that if you remove **DRIVE 0** behind the **UNIT 8/9**, for the reader it's much less confusing

**Comment by Impakt** [comment]
@MauriceMEGA65 ok to close this issue?
