### ISSUE TITLE
Getting Started -> Keyboard section and front-printed non-PETSCII ASCII characters

### ISSUE THREAD

**Issue by KithKanan64** [MEGA65/mega65-user-guide#339]
New users may be confused by being unable to type the  ` { } ~ |\\ _ symbols front-printed on their keyboard using MEGA+_key_ in C64/C65 software including BASIC65.

Currently this information is only found in appendix-keyboard, which isn't included in the print manual (or any of the PDFs except the full mega65-book).

**Comment by gurcei** [comment]
Oh, perhaps another aspect that should be emphasised further in the manual is that these special characters are only visible when using the lower-case character set (not the uppercase character set)

**Comment by gurcei** [comment]
I've tried to respond as follows:

1) Tried to add more details to the FONT command (some keys need MEGA key, others don't, tried refining the table, added the remark on needing lowercase):
![image](https://user-images.githubusercontent.com/20013309/139590536-d92b9959-304c-44a6-a865-9a74c0c47abc.png)

2) In `CH3 - Getting Started`, I also make a mention of the facility there too, just to give the mechanism greater exposure:
![image](https://user-images.githubusercontent.com/20013309/139590548-a11354f6-9128-428d-a26c-b821827e4042.png)
