### ISSUE TITLE
Copyright notice for consideration

### ISSUE THREAD

**Issue by sausagejohnson** [MEGA65/mega65-user-guide#34]
AO:

For the defence of copyright it should be assigned to a single entity. It's also necessary to assert the moral rights of the author to be identified as the author.

I would suggest assigning the rights to MEGA as it will then immediately attract EU copyright protection.

There should be a copyright statement including something like: "This book is copyright under the Berne convention."

Then something along the lines of:

"Paul Gardner-Stephen has asserted his moral right to be identified as the author of this work."

And finally the license for reproduction. Not sure if GPL books is any better than Creative Commons but both of them get abused a lot.

**Comment by Edilbert** [comment]
The book has now an ISBN and EAN13 number.
I think, this is sufficient to protect the copyright of Gardner-Stephen, et al.
