### ISSUE TITLE
Add data files to BASIC65.D81 to make some of the BASIC examples in the manual work

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#348]
Not needed for the hardcopy User Guide, but for the BASIC65.D81 disk image, I would like to have some data files that are referred to in the BASIC examples.

1. RREG, SYS and USR require a file named "ML-PROG"
2. LOADIFF requires .IFF files
3. SPRSAV requires a file named "SPRITEDATA"

**Comment by MauriceMEGA65** [comment]
Do I have access to MEGA65.D81? I cannot find it on Filehost.
If I do not have access, can you please send me some IFF files?

**Comment by gurcei** [comment]
> Do I have access to MEGA65.D81? I cannot find it on Filehost.

I also had a hard time locating it on the filehost, but eventually found it within the "sd card essentials" download (can't recall if it was the "with rom" or "no rom" edition). If you can't locate it, I will try hunt it down for you tomorrow (heading to zzz now ;-))

**Comment by MauriceMEGA65** [comment]
Aha, I will dig into it, good to know where to look. Thanks!

**Comment by gurcei** [comment]
Ah, looks like it was in the 'SD Card essentials' (with rom) download:
- https://files.mega65.org?id=a809e0ae-30ac-42f5-ab9c-766d72fd6331

This one is only available in the private area for registered users/owners. I've extracted it out from there and will drop it here for you:

[MEGA65.zip](https://github.com/MEGA65/mega65-user-guide/files/7457672/MEGA65.zip)

**Comment by MauriceMEGA65** [comment]
Got it and I see the IFF files. Thanks a lot!!
