### ISSUE TITLE
pdf bookmarks for assembly instructions

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#350]
While browsing the pdf looking for BASIC commands, I've found it convenient to browse through them via the pdf bookmarks view:
![image](https://user-images.githubusercontent.com/20013309/137665822-d19370d5-5028-4a44-a960-bccf8968d778.png)

Though for our "Appendix H - 45GS02 & 6502 Instruction Sets" page, none of the assembly language instructions provide such pdf bookmarks.

As a tangential thought to this, I noticed that our TOC lists all BASIC commands in it. I noticed that the C64's reference guide didn't list all commands in its TOC. Could we possibly hide those entries from the TOC and save a few pages that way?

**Comment by lydon42** [comment]
This was added in the [inst-set-makeover](https://github.com/MEGA65/mega65-user-guide/tree/inst-set-makeover) branch.
