### ISSUE TITLE
Considering improving explanation of Amiga + C1351 mouse support

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#361]
I've always found the topic quite confusing, and the settings provided by m65-config hard to grasp.

Folks have walked me through it with their explanations, I 'get it' now, but I wonder if wording could be improved in our docs some way to make it easier for newcomers to grasp what is going on.

Here's some recent discussions on Discord about the matter:

https://discord.com/channels/719326990221574164/720355877701550131/900166090615832577

**Comment by dansanderson** [comment]
For the User's Guide 2nd ed. we've rewritten most of the text, and in v0.96 we've removed the confusing "aggressive" option. Hopefully this resolves the matter.

![CleanShot 2024-02-20 at 02 18 43](https://github.com/MEGA65/mega65-user-guide/assets/408973/02fee161-8a4e-4240-845c-40311fb060d1)
