### ISSUE TITLE
Standardise usage of e.g. and for example

### ISSUE THREAD

**Issue by Impakt** [MEGA65/mega65-user-guide#392]
Might be too much work or maybe im being too picky. Some parts use e.g., and other parts use for example.

The good thing is with a good find/replace tool and some care it's not too much work. Thoughts anyone?

**Comment by gurcei** [comment]
For me, I'm ok with a bit of variation on in this, but if it really bugs you, I won't stop you from ironing it out :)

**Comment by lydon42** [comment]
This is a style-guide topic. Should be discussed, decided and replaced.

**Comment by nobruinfo** [comment]
By awaiting decisions I continue using `for example` in the flow of sentences.

**Comment by dansanderson** [comment]
I have added guidance on "e.g." and "i.e." to the style guide, based on CMoS and other sources.

They're allowed for informality and de-emphasis. They're a common sort of verbal tick for some writers, and we should prefer more formal structures for clarity, but allowing them occasionally fits with a casual voice.

I'm not going to update existing uses all at once. I'll address it as part of larger overall edit of existing material. Some need to be rewritten for clarity, some just need the punctuation updated.
