### ISSUE TITLE
Document use of colon in basic?

### ISSUE THREAD

**Issue by Impakt** [MEGA65/mega65-user-guide#393]
As per this page https://social.msdn.microsoft.com/Forums/sqlserver/en-US/b53dd426-1895-4e45-b8af-28d040bf000d/what-does-this-colon-do-in-vbnet-?forum=vbgeneral

I dont believe the use of the colon is documented in the guide, yet many code examples use it

**Comment by gurcei** [comment]
Ok, added this:
![image](https://user-images.githubusercontent.com/20013309/139782901-efc0b334-0292-4f5f-beb6-616ef60e0fb3.png)
