### ISSUE TITLE
Add dip switch section to User Guide

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-user-guide#394]
Paul suggested that the DIP Switches on the MEGA65 board should be documented in the User Guide.

The switches are (on setting):
1 - Keyboard Flash enable
2 - HDMI Audio disabled
3 - QSPI Flash enable (new)
4 - Boot Slot 2 (new)

As far as I can grep, only switch one is documented in appendix-mega65r2-flashing.tex

**Comment by gurcei** [comment]
Ok, this has been sorted out now.
