### ISSUE TITLE
BASIC example PEN in User Guide has typo

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#396]
Line 130 of the BASIC examples has a REM statement that the chosen color is BLUE.
This is incorrect, and needs to be GREEN.
![Screenshot 2021-10-29 at 19 41 16](https://user-images.githubusercontent.com/75681098/139530262-a88d1edb-ea96-4900-80cc-604a05c09791.jpg)

**Comment by gurcei** [comment]
Thanks, have fixed this and will push the commit soon.
