### ISSUE TITLE
User Guide: use same type of arrows throughout the document

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#403]
See below example: can we have the same type of arrow in both screenshots, will look better?

![Screenshot 2021-11-01 at 21 56 26](https://user-images.githubusercontent.com/75681098/139741268-95bb7a4a-539c-44dd-a78e-c8e7e5696003.jpg)

**Comment by gurcei** [comment]
I don't think I'd do a great job at making them any prettier :D Maybe @Impakt might have the appetite for it, or maybe others, but if we don't get around to it, no worries, I can live with it, they still look readable and informative ¯\_(ツ)_/¯.

**Comment by Impakt** [comment]
I'll have a go at doing the first one, if it looks ok i can photoshop the 2nd one to remove the annotations and re-add some new ones.

**Comment by gurcei** [comment]
Feel like impakt has sorted this one on this PR now:
https://github.com/MEGA65/mega65-user-guide/pull/412

**Comment by MauriceMEGA65** [comment]
Thanks all!
