### ISSUE TITLE
User Guide: update text "MEGA65 Book" --> "MEGA65 Complete Compendium"

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#404]
Since the title of the Book is changed, update also references to it like in below example:

![Screenshot 2021-11-01 at 22 11 49](https://user-images.githubusercontent.com/75681098/139742984-ff2a5ebf-fb1e-4ba5-847a-aba9f09ca1cb.jpg)

**Comment by gurcei** [comment]
I'm feeling like we should keep the 'MEGA65 Book' term as an informal/short-name.

To further emphasise that they are one and the same, I'm happy for a front-cover that mentions both, e.g.:
```
   COMPLETE COMPENDIUM
     THE MEGA65 BOOK
```
I'll also further emphasise the equivalence in the introduction text by bolding the shorter term:
![image](https://user-images.githubusercontent.com/20013309/139778562-326fcd76-e419-4d8a-bce9-e5e8ad7eb6f3.png)
