### ISSUE TITLE
User Guide; unclear sentence

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#405]
I've read below highlighted sentence several times, but still do not understand what it is trying to say:
"..... already in C65 mode....". Should it not be C64 mode?
"... if you do this....". Do what? POKE or GO64?

My proposal is to remove the whole sentence

![Screenshot 2021-11-01 at 22 17 50](https://user-images.githubusercontent.com/75681098/139743907-5568d08e-78d8-4eca-abc7-0732fc5b6895.jpg)

**Comment by gurcei** [comment]
I think I'll change the line to read:

`NOTE: If you perform these POKEs while in C65-mode, the MEGA65 may not function correctly.`

..and indeed, I tried them in c65-mode, the screen goes blank and it freezes up.
