### ISSUE TITLE
User Guide; address of KEY register not mentioned in text

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#406]
The examples eventually makes it clear that the address is 53295.
But, why not mention that in the text? For instance in the same line as were the values 165 and 150 are mentioned.

Not critical by any means, but I found it a bit strange.

![Screenshot 2021-11-01 at 22 33 56](https://user-images.githubusercontent.com/75681098/139745433-0018c69c-c8fa-4320-a287-a3f99d69b464.jpg)

**Comment by gurcei** [comment]
Ok, I've tried to emphasise the address a bit more:
![image](https://user-images.githubusercontent.com/20013309/139777351-c2a57338-0421-4a22-b4ab-df873d5af176.png)

**Comment by Impakt** [comment]
@gurcei i had the same issue, and added the key address here in a PR a few weeks ago. Probably wouldn't hurt to make the mention there in bold too 

![image](https://user-images.githubusercontent.com/1773489/139778599-6781289e-d023-4b62-a77e-4e6f3f3ed488.png)

**Comment by MauriceMEGA65** [comment]
Looks great now, thanks
