### ISSUE TITLE
User Guide: add default setting to the dip switch table

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#407]
Please add the default (factory) setting of the dip switches.
Just by adding "(default)" behind the corresponding text in the "Purpose" column.

![Screenshot 2021-11-01 at 22 43 40](https://user-images.githubusercontent.com/75681098/139746411-313edce8-11aa-4cdb-9102-8902c2d8079e.jpg)

**Comment by gurcei** [comment]
I'd like to, but I'd like confirmation from those in the know first. Perhaps @gardners can confirm?

**Comment by gurcei** [comment]
From this photo in the manual, they all appear to be off by factory default?
![image](https://user-images.githubusercontent.com/20013309/139782332-2c2cdc84-1e2d-4474-b447-c4ed51498ef2.png)

Again, I'd like confirmation of this from @gardners or someone else in the know before proceeding to document it.

**Comment by MauriceMEGA65** [comment]
Agreed. Can we assign it to Gardners? On my iPad it seems I cannot assign it to anyone…

**Comment by gurcei** [comment]
Ok, will do.

**Comment by lydon42** [comment]
Added default column to the dip switch table.
Also clarified dipsw#2 behaviour.
