### ISSUE TITLE
DMODE has too many arguments

### ISSUE THREAD

**Issue by jimnicholls** [MEGA65/mega65-user-guide#409]
The format and usage for DMODE has `DMODE jam, complement, inverse, stencil, style, thick`.  But trying to give this many parameters gives a syntax error.

```
DMODE0,0,0,0,0,1

?SYNTAX ERROR
READY.
DMODE0,0,0,0,1

READY.
DMODE0,0,0,1

?SYNTAX ERROR
READY.
```

**Comment by gurcei** [comment]
Ah good catch, I made some usage notes here, but looks like we overlooked updating the docs based on the findings:
- https://github.com/MEGA65/mega65-user-guide/issues/250#issuecomment-924645725

I'll take a look now.
