### ISSUE TITLE
Default font

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-user-guide#41]
Most proportional fonts provide glyphs in equal width for the digits 0 -> 9.
This makes it easy to align numbers.
The default font in this user guide however has equal widths for all digits but '1', which is narrower than all other digits. This spoils the layout on many pages, even the content pages look awkward with their badly aligned page numbers.
I recommend to switch to a font with digits of equal width.

**Comment by gardners** [comment]
A good point! Do you know of such a font?  Or do we need to override the specific glyph for the digit 1?

**Comment by Edilbert** [comment]
I'll test other fonts.

**Comment by gardners** [comment]
The challenge will be finding one that looks otherwise similar. Also consider making a derived version of current font, with modified glyph, if the license allows us.

**Comment by Edilbert** [comment]
Here is an example of the index page using the current font "GlacialIndifference":
<img width="604" alt="Glacial" src="https://user-images.githubusercontent.com/6380947/68055244-7c57f300-fcf0-11e9-8345-2b87b95ff299.png">

Here is an example with a font from the LaTeX package called "Iwona":
<img width="604" alt="Iwona" src="https://user-images.githubusercontent.com/6380947/68055256-837f0100-fcf0-11e9-9316-dd8d970bedb3.png">

See especially the line with "APPEND . . . 41"

I don't know, where the GlacialIndifference comes from, but I propose to use one of the builtin fonts of the fontspec package. Not necessarily Iwona, but one without the digit '1' quirk.

**Comment by gardners** [comment]
Hmm... GlacialIndifference looks much nicer, I think.  Is it possible to tell LaTeX to take just the 1 digit from another font? Better, GlacialIndifference is an open-source font: https://www.fontsquirrel.com/license/glacial-indifference
This means that we can simply modify the offending glyph...

**Comment by gardners** [comment]
Fontforge can be used to modify glyphs in an OTF font file.
Thus we can just modify the widths of the digits (they are actually all slightly different widths), and give it a new name, like MEGAIndifference, and then we have an ideal solution, without too much work, I think.

What do you think?

**Comment by Edilbert** [comment]
OK, I'll try to edit the font file.

**Comment by sausagejohnson** [comment]
Agreed GlacialIndifference is so much nicer.  +1 to a FontForge edit. https://cargocollective.com/hanken/Glacial-Indifference-Open-Source-Font

**Comment by Edilbert** [comment]
The new font family "MegaGlacial" is copied from "GlacialIndifference" with all digits set to equal width and the glyphs centered inside the width. See screenshot:

<img width="604" alt="Bildschirmfoto 2019-11-02 um 08 15 59" src="https://user-images.githubusercontent.com/6380947/68067589-8eb24b00-fd49-11e9-885f-66cf466a4807.png">

**Comment by gardners** [comment]
Well done, and looks super sweet!
