### ISSUE TITLE
EDMA sub and mod arguments

### ISSUE THREAD

**Issue by jimnicholls** [MEGA65/mega65-user-guide#410]
The usage for EDMA's sub and mod arguments say "(see chapter on DMA controller)". This should be proper reference to the F018-Compatible Direct Memory Access (DMA) Controller chapter to the chipset reference.

Although that chapter in the chipset reference doesn't mention subcommands or modifiers.

**Comment by nobruinfo** [comment]
@jimnicholls I'm also confused:

![grafik](https://user-images.githubusercontent.com/67829169/209140451-7973e22e-5c38-4d02-bbbd-60f646ee239b.png)

@gardners Could *modulo* be meant?

**Comment by dansanderson** [comment]
I believe the correct fix for this is to rescind the "subcommand" and "mode" (sic) parameters from the EDMA command. Modulo is not yet implemented in the DMA, the EDMA command does not set it as a 16-bit value anyway, and the only useful values for the "subcommand" are to set "hold" addressing. Direction and I/O register mapping are undocumented and (possible but) not easy to use.

Recommended ROM change: https://github.com/MEGA65/mega65-rom-public/issues/36

I'll leave the doc bug open to track cleaning up the EDMA BASIC reference, if only to remove "sub" and "mod" until we're sure what we want the API to be.

**Comment by nobruinfo** [comment]
@dansanderson Aaahhh, those are actually two different features. Okay. I'd also understand that "not yet implemented" is maybe not what we want to have in the manuals - maybe more for an "ideas" or "roadmap" page in Confluence or a place alike.
Are you actually saying the ticket here could remain open until the feature was implemented? IMHO it would be sufficient to have https://github.com/MEGA65/mega65-rom-public/issues/36 open as the sole reminder. Of course it is up to you sterring folks on how to handle.

@jimnicholls To you as the o.p. of this ticket I would say your ticket consists of two requests:
1. For the referencing could you please recheck in a recent version of the manuals like [this one](https://builder.mega65.org/job/mega65-user-guide/job/master/lastSuccessfulBuild/artifact/mega65-book.pdf#page=234) (page 12-36, towards the end of the page) ?
2. Is it okay to track your input on how to handle EDMA in BASIC as suggested by @dansanderson ?

**Comment by dansanderson** [comment]
I agree that, in general, the manual shouldn't document unimplemented features. Where appropriate, the deeper technical reference in the appendices may retain some of this to document the "specification" of a Commodore 65, and some unimplemented features may require "reserving" space in memory or data records for future expansion. The BASIC reference should only describe implemented supported behaviors. (Most of the manual was written in earlier days of the MEGA65 project when writing down the intended future state was the best way to keep track of things, but IMO it's time to clean those out and capture them somewhere else, as you suggest.)

I'd like this ticket open to track cleaning up the BASIC reference. The other ticket is for improving the implementation, which can add more documentation if the chosen implementation lights up features. Either the before state or after state will require doc changes.

**Comment by dansanderson** [comment]
I have removed the non-functional arguments from the BASIC reference entry for EDMA. We can add new documentation when this works better in the ROM. In the 2nd-edition branch.
