### ISSUE TITLE
no pure 6502 CPU

### ISSUE THREAD

**Issue by manni199** [MEGA65/mega65-user-guide#430]
I learned that the Mega65 uses a 45GS02 for the C64 mode. There is no pure 6502 CPU at all in the Mega65.

So Page H-13 should be revised somehow. And on page H-16/H-17 should be mentioned that the ‚unintended‘ commands are not implemented at all. There are no illegal opcodes in C64 mode.
The ‚unintended‘ commands should stay in the manual, I like that.

(Complete Compendium, November, 4th 2021)

**Comment by lydon42** [comment]
I will fix this in the inst-set-makeover branch.

**Comment by lydon42** [comment]
A note was added.
