### ISSUE TITLE
Freezer: rename Device # to Unit #

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#434]
A device with an ID number (8, 9, 10, 11, etc) is called a Unit according to the manual.
Therefor I think **DEVICE #** needs to be renamed to **UNIT #** in the Freezer

![Screenshot 2021-12-06 at 08 29 25](https://user-images.githubusercontent.com/75681098/144806979-4a3cdf56-1a5f-4852-ae79-281e88c5bded.jpg)

![Screenshot 2021-12-06 at 08 33 02](https://user-images.githubusercontent.com/75681098/144807009-0d2d2eb3-5088-42a3-8d42-cfcaefd6f5fb.jpg)

Note:
Correct me if I'm wrong, but this is how I interpret the use of Device and Unit, and which makes the situation clear to me:
_DEVICE is something I can hold in my hands, UNIT is basically the ID that the computer uses to speak to that device_

**Comment by Rhialto** [comment]
UNIT would also be more consistent with Basic 4.0 and higher which uses U8 for this, and D1 for indicating the drive within the unit.

**Comment by lydon42** [comment]
Renamed in mega65-freezemenu#44

**Comment by MauriceMEGA65** [comment]
Thank you!
