### ISSUE TITLE
fix broken minitocs for chapter front pages

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-user-guide#44]
There are some conflicts of "aeb-minitoc" with other packages.
Fix display of TOC for chapter front pages.

**Comment by Edilbert** [comment]
Well, I spent some hours tracking down the source of this problem.
This is what I found so far:
The miniTOC was handled by the package {aeb-minitoc}. This package is not part of the texlive distribution, but a separate file included in this repository. aeb-minitoc reads the file "userguide.toc" in order to retrieve all necessary information. Alas, the format of the toc-file changes from time to time and this is the cause, why minitoc doesn't work anymore with the actual release of texlive. I downloaded the newest version of aeb-minitoc, but this doesn't work either. There is an option clash with the package {hyperref} besides several other errors like "Two \documentclass or \documentstyle commands".
Currently I see no easy way to get the issue resolved and think about some options:
1) No TOC on chapter front pages
2) Switch from aeb-minitoc to minitoc. (A lot of work and not so fancy as aeb-minitoc)
3) Edit "aeb-minitoc.sty" until it gives the desired result. (Even more work: understand the mechanics of aeb-minitoc and try to change it) This may also work only until the next update of texlive.

I would like to get your comments and appreciate any help.
Edilbert

**Comment by Edilbert** [comment]
Meanwhile I was successfull in extracting the correct "aeb-minitoc.sty" from "aeb-minitoc.dtx" in an updated version.
This solves the problem with the entry "protected@file@percent" in the toc-file.
But the issue remains, that the aeb-minitoc reads the toc file, but doesn't create tables.

**Comment by gardners** [comment]
Argh! Or do we just make some magic script that extracts the information from the tex files and makes a little tex file for each chapter that we \input from the chapter tex?  It's probably easier, less fragile and easier to maintain than Yet Another Latex Package?

**Comment by Edilbert** [comment]
Interesting idea. That would also solve the problem of the chapters with too many sections, which would not fit on the front page. They could be hand edited, for example, to show contents of the starting letter, A-C, D-F, etc. instead of listing 190 commands. I like the idea and we could drop the {aeb-minitoc} completely.

**Comment by gardners** [comment]
Yes, I think it makes a lot of sense. I'd still make the little program (probably in C or python) automatically generate everything, however, rather than post-tuning by hand, so that life stays simple for the normal case. It might be we have different modes of running it for different chapters that have different TOC behaviour.  Not too hard to do, I think.

**Comment by Edilbert** [comment]
Finally I was successfull in getting {aeb-minitoc} to work again. The key was the correct update procedure for the file {aeb-minitoc.sty} via the utility "docstrip", which was new for me. If {aeb-minitoc} works flawlessly in the future, we can stick to it. Otherwise it's good to keep the discussed alternative in mind.
