### ISSUE TITLE
Need information about core boot selector when using configuration menu

### ISSUE THREAD

**Issue by jesperrula** [MEGA65/mega65-user-guide#440]
When saving the configuration in the configuration menu, the machine will boot into slot 0 core no matter what. Next restart it will boot to the selected slot. This violates the Principle Of Least Surprise.

Ref. to https://github.com/MEGA65/mega65-core/issues/524 for more information

**Comment by lydon42** [comment]
This is hopefully temporary and should not go into the manual. Better create a filehost FAQ article for this.
