### ISSUE TITLE
D07B register description is only the word "Number" in the user guide

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-user-guide#442]
According to Johan on discord: D07B register in the documentation is denoted with "Number" only as the description.

In the iomap.txt:

GS $D07B VIC-IV:Number of text rows to display

I _think_ the problem, that register descriptions should have a short name first (with all capital letters) then the description. I don't know how these are processed, but I guess the problem that missing the short name, thus the first word "Number" is included in the table. Instead, the table should contain a capitalized identifier and then an explanation for that identifier under the table ("Number of text rows to display") to match the other registers.

**Comment by lydon42** [comment]
needs to be fixed in core, added to my list.
