### ISSUE TITLE
Keyboard matrix chart is incorrect

### ISSUE THREAD

**Issue by M3wP** [MEGA65/mega65-user-guide#443]
The keyboard matrix chart on page D-5 of the book (chapter "C65 Keyboard Matrix") is incorrect in that the up arrow and left arrow keys should be displayed with the same graphic style.  Currently, the up arrow is being displayed in the same style as the cursor keys which is incorrect.

**Comment by lydon42** [comment]
Keep an eye on #422 when fixing this!

**Comment by lydon42** [comment]
D-15f does show left arrow as a plain arrow, all other arrows as keys.

**Comment by lydon42** [comment]
To also add this here from #422
The current state is confusing. ARROW KEYS lists the left and up arrow as black on white. Which is in contrast to every other normal key, that is white on black. In reality all alphanumeric keys are the same as the left and up arrow. The cursor keys are the ones that are different on the keyboard.

**Comment by dansanderson** [comment]
This is now corrected. We can talk about re-styling our arrow vs. cursor keys separately; I used our current style for consistency.

![CleanShot 2024-07-09 at 17 51 03](https://github.com/MEGA65/mega65-user-guide/assets/408973/9bedbef9-6c5b-4141-a379-b2c70c38ffa9)
