### ISSUE TITLE
Replace cover art of User Guide by new cover made by @Hojo

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#445]
To bring the User Guide cover in sync with the other MEGA65 manuals.

See cover: 
https://cdn.discordapp.com/attachments/720355877701550131/904793282045939773/uguide2.jpg

And response @Hojo:
https://discord.com/channels/719326990221574164/720355877701550131/939911557654151171

**Comment by lydon42** [comment]
Linked to #444 ?

**Comment by gardners** [comment]
The last commit on that pull request #444 doesn't build. Possibly because the image is one pixel too short.

This one should be easy to fix, if someone can get the correct image.

**Comment by nobruinfo** [comment]
@gurcei Is here something to be done? `frontcover.tex` currently is:

https://github.com/MEGA65/mega65-user-guide/blob/d462dd9b537853c69f2ff0329447c705a2c0cc78/frontcover.tex#L15-L21

Otherwise please close this ticket.

**Comment by MauriceMEGA65** [comment]
The new cover is still not implemented

**Comment by nobruinfo** [comment]
@MauriceMEGA65 I see now what is meant. The above given .jpg is of a different aspect ratio and showing a Mega 65 which is a little "fat". I think if I'd copy this into the books some white borders would appear. So maybe a Latex specialist should look into this ticket first.

**Comment by MauriceMEGA65** [comment]
The current used blue cover is a totally different cover than the colorful cover made by Hojo. My suggestion/request is to use the cover made by Hojo so that the User Guide has the same cover type as the other MEGA65 books

**Comment by MauriceMEGA65** [comment]
This is the requested cover: 
![](https://cdn.discordapp.com/attachments/720355877701550131/904793282045939773/uguide2.jpg)

**Comment by nobruinfo** [comment]
@MauriceMEGA65 Do you want me to force it in and generate a preview PDF for you?

![grafik](https://user-images.githubusercontent.com/67829169/209559722-0058fd0d-f324-4e2a-bce5-1493ed044272.png)

**Comment by MauriceMEGA65** [comment]
No pdf for me needed I think. If you are able to replace the cover, all is great

**Comment by MauriceMEGA65** [comment]
Hojo created the files. Perhaps he can help you provide a correct aspect ratio file, he made the cover for the other manuals as well

**Comment by dansanderson** [comment]
I added a white pixel row to the bottom of the new cover image, so it matches the other covers. I didn't notice any build issue or visual artifact with the previous image but now it's precise. (2nd ed branch for now.)
