### ISSUE TITLE
Typo in Monitor Appendix

### ISSUE THREAD

**Issue by johnwayner** [MEGA65/mega65-user-guide#451]
B : BITMAPS section's remarks has a typo:

The B command displays the contents of memory cells bitwise by printing an asterisk for 1 and a **dor** for 0. The special arrangement of character data with 8 bytes forming one character cell, is considered. 8 characters are displayed for each call.

"dor" should be "dot".

**Comment by lydon42** [comment]
@johnwayner is this closed with @gurcei 's merge? Then please do so :)
