### ISSUE TITLE
C64/C65 code is broken for C64

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-user-guide#458]
Appendix M of the book, the section on Full-colour Sprite mode.

The example program to show a full-color Sprite is meant to work in both C64 and C65 mode. However, on line 1010 of the program the commands BEGIN and BEND are used, and they don't work in C64 mode. They can just be removed without affecting the functionality.

**Comment by lydon42** [comment]
Don't you want to get your hands dirty and do a pull request for this?
