### ISSUE TITLE
CHDIR is incorrectly alphabetized in the BASIC reference

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-user-guide#459]
**Describe where we can find the problematic topic**
User's Guide, BASIC reference appendix, page 93 as of this writing, CHDIR entry.

**Describe the solution you'd like**
CHDIR is currently alphabetized above CHARDEF, and should be below it.

(Apologies for not just submitting a PR, I don't have a local doc build set up yet and didn't want to forget this. :) )

**Comment by Edilbert** [comment]
Thanks for the report.
