### ISSUE TITLE
Instruction Set documentation enhancements

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-user-guide#472]
Collection of assembly issues, fixed in [inst-set-makeover](https://github.com/MEGA65/mega65-user-guide/tree/inst-set-makeover) branch.

- #324 
- #350 
- #430 
- #469 
- #470 
- #471

**Comment by nobruinfo** [comment]
@lydon42 I'm not a product owner here, but none of the listed tickets are open any longer. Can this one be closed as well? Thank you.
