### ISSUE TITLE
Missing or broken references in developer guide

### ISSUE THREAD

**Issue by nils-eilers** [MEGA65/mega65-user-guide#476]
Some references are broken or were forgotten, resulting in just two question marks in the manual

~~~
mega65-developer-guide.log:LaTeX Warning: Reference `hyppo:cdrootdir' on page 97 undefined on input line 5
mega65-developer-guide.log:LaTeX Warning: Reference `hyppo:cdrootdir' on page 108 undefined on input line 
mega65-developer-guide.log:LaTeX Warning: Reference `cha:configuring' on page 167 undefined on input line 
mega65-developer-guide.log:LaTeX Warning: Reference `sec:bitstreamfiles' on page 167 undefined on input li
mega65-developer-guide.log:LaTeX Warning: Reference `sec:installingrometc' on page 168 undefined on input 
mega65-developer-guide.log:LaTeX Warning: Reference `cha:configuring' on page 168 undefined on input line 
mega65-developer-guide.log:LaTeX Warning: Reference `cha:configuring' on page 168 undefined on input line 
mega65-developer-guide.log:LaTeX Warning: Reference `cha:cores' on page 169 undefined on input line 263.
mega65-developer-guide.log:LaTeX Warning: Reference `cha:configuring' on page 169 undefined on input line 
mega65-developer-guide.log:LaTeX Warning: Reference `sec:bitstreamfiles' on page 204 undefined on input li
~~~

**Comment by nobruinfo** [comment]
@dansanderson I see the first reference `hyppo:cdrootdir` working properly in my local pull. The same source files are in my latest pull request. I think it might be because in *Travis* each book is only run by calling `make` just twice. We could try calling it up to four times. But I'm not sure whether to throw this change in `.travis.yml` at you. ;)

```diff
  - make mega65-book.pdf || true
+ - make mega65-book.pdf || true
+ - make mega65-book.pdf || true
  - make mega65-book.pdf
```

What the first warning listed in the ticket text actually gives is a completely missing section for the *Reference 'hyppo:cdrootdir'* which is quite bad. Also I'm preparing another pull request to address the page break of this invisible section.

![grafik](https://user-images.githubusercontent.com/67829169/209155189-422cdf93-c870-42e6-a943-078ef31b80fc.png)

**Comment by nobruinfo** [comment]
There is a reference from the now visible section `hyppo_cdrootdir` to `\hypporef{setdisk}` which does not exist. I have no idea what would make sense here:

![grafik](https://user-images.githubusercontent.com/67829169/209180439-a43a7701-852b-4d71-9dd1-c423e558dc67.png)

**Comment by gurcei** [comment]
Trying to dig into the `mega65-core` repo, `src/hyppo/dos.asm` source to try figure out this mystery on what `\hypporef{setdisk}` was meant to be.
- `hyppo_cdrootdir` seems to equate to `trap_dos_cdrootdir` within the `dos.asm` file. Internally, it does the following:
```
trap_dos_cdrootdir:
	ldx hypervisor_x
	jsr dos_cdroot
	jmp return_from_trap_with_carry_flag
```
- that `jsr dos_cdroot` implementation looked like it had a clue:
```
dos_cdroot:
        jsr dos_set_current_disk
        bcs dos_cdroot_current_disk_already_set
```
- so I suspect what @gardners intended to mean was that any returned output would be equivalent to something that called `dos_set_current_disk:` routine directly.

- The only other trap where the `dos_set_current_disk` routine is used is within `trap_dos_select_drive:`, so 'maybe' he might have intended to link to `hyppo_selectdrive`, though the entry in the manual command doesn't presently describe any outputs...

Taking a look at the source for it, upon failure inside `dos_set_current_disk`, this will later cause a `jmp return_from_trap_with_failure`, which returns the dos-errorcode via the A register (which would contain the value $80 = #dos_errorcode_no_such_disk).

__Conclusion__:
- I think the link should be to `\hypporef{selectdrive}`
- As the `hyppo_selectdrive` doesn't have any 'Outputs:' field, I believe it's referring to the 'Errors:' field (which can only return an error-code of $80, as far as I know).
- maybe @gardners can confirm

**Comment by nobruinfo** [comment]
@gurcei Thank you for this investigation. I would never come to any conclusion whatsoever.

**Comment by nobruinfo** [comment]
@nils-eilers Could you please verify that all of your suggestions are met and eventually close this ticket? Thank you in advance.
