### ISSUE TITLE
Improve explanation of 'hot registers'

### ISSUE THREAD

**Issue by gurcei** [MEGA65/mega65-user-guide#477]
**Describe where we can find the problematic topic**
The current explanation of 'hot registers' within the manual is confusing, terms like 'precise vernier registers' are mentioned, but not explained.

**Describe the solution you'd like**
After discussions in discord:
- https://discord.com/channels/719326990221574164/719326990221574168/989708685628551178

I'm feeling like the term 'vernier' adds more confusion than enhances understanding, the term is only ever used twice in the entire manual, so I suggest dropping the term.

So I'm in favour of rather using the term 'precise registers' rather than 'vernier registers' of 'precise vernier registers'.

I also feel like in order for the penny to drop on this topic for new users, an example should be given, such as the D060-D063 example from the discord thread.

I might put my hand up to do this, time permitting, but happy if anyone else wants to try do a PR for it.

**Comment by dansanderson** [comment]
How about:

```
Some VIC-IV registers support features similar to the VIC-II and VIC-III, but with expanded capabilities. For backwards compatibility, writing to specific VIC-II and VIC-III registers also causes related VIC-IV registers to reset with consistent values. If you write to any of these registers, you may need to update the VIC-IV registers after you do so.

For example, the lower four bits of register \$D018 (\textbf{CB}) set the VIC-II character set address, as a multiple of 1 KiB. VIC-IV can locate the character set to any 24-bit address using \$D06A (\textbf{CHARPTRBNK}), \$D068 (\textbf{CHARPTRLSB}), and \$D069 (\textbf{CHARPTRMSB}). If you set CB, the VIC-IV registers will also be updated to match.

The complete set of VIC-II registers that affect VIC-IV registers include:

\begin{itemize}
\item \$D011 (53265)
\item \$D016 (53270)
\item \$D018 (53272)
\item \$D031 (53297)
\item The VIC-II bank bits of \$DD00 (56576)
\end{itemize}

This "hot" behavior of the VIC-II registers is intended primarily for legacy software. It can be disabled by clearing the HOTREG signal: bit 7 of \$D05D (53341).
```

**Comment by gurcei** [comment]
@dansanderson - Yes this is looking much better than what was there already to me. Maybe I'm happy for this term "precise registers" to still get a mention somewhere though, as there are other locations within the manual that do use the "precise" term (so I think it has more traction than "vernier").

I liked you list of affected vic-ii registers, I wonder if it's worth putting them in a table so that we can clarify which vic-iv registers they map to (in the "hot register" sense)

**Comment by gardners** [comment]
I agree that having some worked examples that show what happens when you touch one of the hot regs when activated does to other registers, makes a lot of sense.

**Comment by gardners** [comment]
What I have done instead, is to document all the registers that get mashed by HOTREGS, so that people can understand its effects, and also be able to get some clues as to how to change video modes to do what they want.

**Comment by gardners** [comment]
Can someone please proof-read and close when they are happy with the fixes?

**Comment by dansanderson** [comment]
Added comments to the changes in Github.

**Comment by dansanderson** [comment]
I believe this is in good shape now. Closing.
