### ISSUE TITLE
Autogenerate PDFs for print

### ISSUE THREAD

**Issue by lydon42** [MEGA65/mega65-user-guide#478]
User Maurice on discord suggested that we also provide print PDFs, so users can print them without having to remove screen elements like the red borders around links.

**Comment by lydon42** [comment]
Some findings:
- there where no offset printing versions generated, only the RGB one.
- manuals where digitally printed
- so probably the ref frames where also manually removed?

**Comment by lydon42** [comment]
b56cb34e38444ccce4c02375e2c7fcbca8f67d14
f81083be63f9242ff920d2b189580b1c07026506
b52a9cb91a84ad8ef351e6efa17f9ab3d1f8570b
a8ba921b6ded078da3994f6692a18131d645682e

**Comment by gardners** [comment]
I _think_ that this one is complete, between the hyperref fixes for removing the boxes, and the auto-generation of all CMYK versions of the PDF.  Close when content @lydon42

**Comment by dansanderson** [comment]
Closing per comment above.
