### ISSUE TITLE
Addressing modes description improvement

### ISSUE THREAD

**Issue by Rhialto** [MEGA65/mega65-user-guide#481]
**Describe where we can find the problematic topic**

In the Mega65 book appendix H. chapter "ADDRESSING MODES". This seems to be in TeX file `appendix-instructionset.tex`. 

Here are descriptions of the addressing modes by name. But only for the first two an example is given of what the an instruction using it looks like.

I was at first confused with the names/descriptions of "Base Page (Zero-Page) Y Indexed Mode" and "Base Page Indirect Y-Indexed Mode". The former was described first but I'd wager that the latter is used much more often, and in the long names the word "Indirect" got kind of lost. I was wondering for a while why the description of the former mode didn't match "LDA (zp),Y", before I noticed that that mode was described later.

Also the naming doesn't always seem consistent: "(Zero-Page)" is only sometimes included, and makes the name confusingly long. And is it "Y Indexed" or "Y-Indexed"?

**Describe the solution you'd like**
I'd like an example of how each addressing mode is written in common assembler notation.
Also, the consistency in the names of the addressing modes can be improved a bit.

**Comment by gardners** [comment]
Relative and stack indirect relative modes still need to have examples. But otherwise, I believe the rest of this request is complete.

**Comment by gardners** [comment]
@Rhialto please check the updated text, and if you are happy with it, close the issue.
