### ISSUE TITLE
Addition to 'BASIC tokenisers' chapter.

### ISSUE THREAD

**Issue by ArthurJordison** [MEGA65/mega65-user-guide#493]
I don't know if you're aware of 'CBM prg Studio', which is a popular IDE for the likes of the Commodore 64.

I'm currently adding support for the Mega65 and BASIC 10 so I was wondering if you could add it to this chapter? The latest version of CBM prg Studio with Mega65 support hasn't been released yet but I'm hoping to by the beginning of October.

**Comment by gurcei** [comment]
Happy to hear that you're adding MEGA65 support in :-) Yep, I'm happy to add CBM prg Studio to the list in this chapter.

Also, just a side-note on the term BASIC 10. The MEGA65 community, particularly @Edilbert , has been making many great improvements to Commodore's original BASIC 10 (many new tokens added, and existing commands have been improved too. This new/improved version of BASIC is now referred to as BASIC 65 (to help distinguish it from where Commodore left things at with BASIC 10).

**Comment by gurcei** [comment]
Ok, I've added this with a quick edit via my phone (formatting might not be ideal, but can be improved later). Thought I'd mention a few other IDEs too, just so they're all on the radar in this chapter.
