### ISSUE TITLE
Audio DMA. Manual says it's halted during a DMA transfer.

### ISSUE THREAD

**Issue by MirageBD** [MEGA65/mega65-user-guide#496]
The manual says:

"When ADDRLSBTRIG has been written to, the DMA job completes immediately. Unlike
on the C65, the DMA controller is part of the processor of the MEGA65. This means
that **the processor stops trying to execute instructions or fetching audio samples for
DMA audio playback until the DMA job has completed**"

This seems to suggest that Audio DMA is halted during DMA transfers, which it isn't.

**Comment by gardners** [comment]
That was the original behaviour. You are quite correct that audio DMA now is the only thing that can interrupt normal DMA (apart from reset)

**Comment by MirageBD** [comment]
Thank you!
