### ISSUE TITLE
Add some info about 53276 location for SPRCOLOR

### ISSUE THREAD

**Issue by heath8041** [MEGA65/mega65-user-guide#509]
Problem:
the basic reference command SPRCOLOR describes that you have to use it to set multi color sprites up, however there is no note about how to turn multi-color sprites on! I found this incredibly frustrating as a new user trying to get multi-color sprites to work. Finally found the answer in the C64 programmers guide. page 136

**Describe the solution you'd like**
It'd be super great if you could just add a note like : (Copied directly from C64 programmers reference p136)

To switch a sprite into multi-color mode you must turn ON the VIC-II control register at location 53276 ($D01C) . The following POKE does this:

POKE 53276, PEEK(53276) OR (2↑SN)

where SN is the sprite number(0 to 7).
To switch a sprite out of multi-color mode you must turn OFF the VIC-II control register at location 53276 ($D01C) . The following POKE does this: 

POKE 53276, PEEK(53276) AND (255-2↑SN)

where SN is the sprite number(0 to 7).

**Describe alternatives you've considered**
I haven't found any alternatives to setting this control register for the VIC

**Comment by dansanderson** [comment]
The last argument to the SPRITE command enables or disables multi-color mode for the sprite. The example under SPRCOLOR does this:

```
 10 SPRITE 1,1,2,,,,1  :REM TURN SPRITE 1 ON (FG = 2)
 20 SPRCOLOR 4,5       :REM MC1 = 4, MC2 = 5
```

I added a remark to SPRCOLOR about this. Let me know if that's not working for you.
