### ISSUE TITLE
More memory map detail: bank 1, base pages, M65 ROM uses of RAM

### ISSUE THREAD

**Issue by dansanderson** [MEGA65/mega65-user-guide#516]
**Describe where we can find the problematic topic**
appendix-memorymap is a great start and contains good descriptions of important memory topics. It could use more detail on how memory is used by the default system. For example, some uses of bank 1 (CBDOS, BASIC variables) are still folk knowledge at the moment, and others (colour RAM) are in the book but not in a visual or tabular summary form.

Another useful piece of information in my notes but not in the book is the ROM's use of base pages, and likely candidates for base pages for programs that want to retain compatibility with BASIC (such as to be able to return to BASIC after running). $1600 is an unused page, for example.

**Describe the solution you'd like**
Add prose descriptions of the uses of bank 1 by the MEGA65 kernel and BASIC. (A prose description exists in this appendix for colour RAM.)

Review kernel and BASIC uses of banks 0-5, and make sure they're represented. Consider a visual or tabular representation of MEGA65 ROM uses of RAM.

Consider a high level overview of how the ROM uses bank 0. The "CPU Memory Banking" section has some good info, but it doesn't answer common questions. Answer the question, "What page can I use as a base page if I want to leave page zero for BASIC?"

More generally, answer the question, "Where can I put code and data if I'm not completely disabling the ROM for this session?"

**Comment by dansanderson** [comment]
From Leica:

```
0.2000 - 0.f6ff  BASIC program text
0.f700 - 0.feff  scalar variables (max. 256)
0.f000 - 0.ffff  free
1.0000 - 1.1fff  CBDOS buffers and variables
1.2000 - 1.f6ff  arrays (bottom) & strings (top)
1.f700 - 1.f7ff  free
1.f800 - 1.ffff  mirror of first 2K of color RAM
2.0000 - 2.ffff  ROM
3.0000 - 3.ffff  ROM
4.0000 - 4.ffff  BASIC bitplane graphics
5.0000 - 5.ffff  BASIC bitplane graphics
```

**Comment by nobruinfo** [comment]
@dansanderson Maybe #429 #439 and this ticket could actually be just one.

**Comment by dansanderson** [comment]
Good point. At the risk of looking self-important ;) I think I'll resolve those in favor of this one.

Those refer to a C65 memory map which is more detailed, but that's detail that deserves to be in our Book. We should also review it for anything that has changed in the MEGA65 ROM. https://65site.de/downloads/c65_rom_memory_map_20201109.pdf

**Comment by dansanderson** [comment]
All of these concerns are resolved with the new memory chapter. Closing.
