### ISSUE TITLE
Incorrect example for DO

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-user-guide#521]
**Describe where we can find the problematic topic**
In the Basic guide in the printed book that comes with the computer, in the section for the keyword DO

The last example includes the line:
20 DO I%=I%+1
This code doesn't work.

**Describe the solution you'd like**
Add a ":" after DO.

**Comment by MauriceMEGA65** [comment]
When I open a recent version of the User Guide, I see the correction is already made(?)

**Comment by fredrikr** [comment]
Sorry, my bad. I tried to find this section in the repo, but failed.
