### ISSUE TITLE
Errors in Base-Page Quad Indirect Z-indexed Mode

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-user-guide#528]
In section H in the MEGA65 Book, (https://github.com/MEGA65/mega65-user-guide/blob/master/appendix-instructionset.tex#L518 ):

![image](https://user-images.githubusercontent.com/1001548/215282369-251ffdc8-e521-44a7-b48c-d0e3c6bdf9d0.png)

There are several errors in this:

* The calculation of the final address assumes the address is stored with the high-byte first, which is incorrect
* The calculation of the final address says Y is added, when in fact Z is added
* The sample instruction says $12, when the text above it says the address is stored at $20.

**Fixing it:**

The text above the sample instruction can remain, if you:

1. change the sample instruction to read LDQ ($20),Z
2. change the first sentence in the text below the sample instruction to this: "would read the contents of memory location \$CDAF (i.e., \$CDAB + Z) -- \$CDB2 and store the result in the Q Pseudo Register."

**Comment by dansanderson** [comment]
Looks like I fixed this and forgot to resolve it. :)
