### ISSUE TITLE
Missing in User Guide: C65 BASIC command LINE INPUT

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#533]
LINE INPUT is missing in the User Guide.
Perhaps on purpose it is left out, but it seems to work: https://discord.com/channels/719326990221574164/805252939593416705/1095934545330704495

Please add LINE INPUT in case it is just forgotten (and not on purpose left out).

**Comment by lydon42** [comment]
What's wrong with the LINE INPUT on page B-145 in the book or 144 in the basic65 reference?

**Comment by MauriceMEGA65** [comment]
C65 spec, page 133:
_LINE  INPUT  allows  the  program to input a string which includes any
PETSCII  character  (including  colons, commas, imbedded spaces, etc.)_

It's covered in the C65 spec under "INPUT", and also briefly mentioned in the MEGA65 User Guide under "INPUT", but no further explanation or example provided.

**Comment by dansanderson** [comment]
Added in 2nd-edition.
