### ISSUE TITLE
Enhancement: Additional PLAY command documentation

### ISSUE THREAD

**Issue by c64cryptoboy** [MEGA65/mega65-user-guide#534]
**Describe where we can find the problematic topic**
Chapter 2 "BASIC 65 Command Reference", PLAY command section

**Describe the solution you'd like**
Would be nice if there were some additional instructions.  My suggestions:

1) The PLAY command's modulation "M" option isn't defined.  Empirically, it seems to be a ROM-controlled vibrato, where the intensity (from 1: low, to 9: high) is not the speed of the vibrato, but the +/- frequency variation from the base pitch.

2) The octave "O" parameter is not described, apart from its allowed range (0 to 6).  Could tell users that a given octave covers C through B (not A through G).

3) I (naively) expected a C128 BASIC sound program to work on the MEGA65, which it, of course, didn't. ;)  Might be nice to tell people that while MEGA65's BASIC sound commands look very similar to the C128, there are important differences.  Specifically, the MEGA65 has improved the PLAY command by restricting each string (to be performed) to a single voice, while the C128 requires interleaving the voices together and can require complicated orderings for correct playback.

4) Small stuff:  Could mention that accidentals (sharps/flats) go before notes, not after notes as they do in sheet music.  Also might be nice to display the available note durations in duration order (as the C128 reference did: W, H, Q, I, and S) instead of alphabetical order.

I'm happy to make a pull request if there's interest.

**Comment by dansanderson** [comment]
All agreed! Feel free to submit a pull request. I'm hoping to do a full testing and polish pass over the BASIC reference soon.

**Comment by gurcei** [comment]
Fine with a PR on this, just some thoughts on my end:

- on point 1, the M modulation is defined in the manual, though admitedly, not as accurately as you have described it :-)

```
The modulation directive will modulate your note by the magnitude you specify (1-9), or use 0 not to use it.
```

At the time, I felt like it was a sufficient description for the musical layman, not wanting to get bogged down in the details, so feel like if this description is to be enhanced with more accurate detail, could it be added after this first sentence so that the layman audience still gets the gist, while the more musically inclined reader can appreciate the details that follow it.

- on point 3, agree, maybe this aspect could be added described in the 'remarks' section towards the end

**Comment by c64cryptoboy** [comment]
> At the time, I felt like it was a sufficient description for the musical layman

The documentation is great -- kudos to any/all that were involved, and I looking forward to having the printed manual on my 8-bit shelf.  I've only recently started looking at anything MEGA65-releated, so I have a set of fresh eyes and just thinking about stuff that wasn't obvious to me until I actually tried it out.  (e.g., the only "modulation" I had seen in the user's guide prior to the PLAY command was the ring modulation in the ENVELOPE command, but they're not related.)

> on point 3, agree, maybe this aspect could be added described in the 'remarks' section towards the end

Does it make sense to have a paragraph that introduces BASIC sound capabilities, apart from any individual BASIC command section? If that were desired, it could also be a place to compare the C128 and MEGA65 sound commands.  In looking at the C128 and MEGA65 manuals, I see they both have ENVELOPE, FILTER, PLAY, SOUND, TEMPO, and VOL (with RPLAY being new with the MEGA65).  FILTER adds a new 1st parameter for SID # (1 or 2), and the SOUND voice parameter now ranges from 1 to 6 (instead of 1 to 3).  Other than that, it's just the PLAY command that's different.  Very similar overall.  If there is interest, I could take a stab at writing it.

**Comment by dansanderson** [comment]
In general the manuals need substantial new non-reference chapters for concepts and tutorials. For now we're letting material accrue in reference chapters, and if it's only one or two more paragraphs it can live (maybe temporarily) in the PLAY entry of the BASIC reference.

I wrote one of the Digests on SID sound and the PLAY command that I kinda thought could be repurposed into a chapter on BASIC music and sound. If I can get my act together I'll be doing some drafting work this summer on those non-reference chapters, including reworking the reference appendices to refer to the tutorial chapters so they can go back to being concise. We can share the load if you like, just saying that's what I have in mind. :)

**Comment by dansanderson** [comment]
P.S. Personally I would put comparisons to other Commodore products in an appendix. I have research notes and an outline for such an appendix that covers all of the BASICs: 2 to 7 to 10 to 65. I would prefer the main material to refer to BASIC 65 exclusively, as if it were a real standalone product.

**Comment by c64cryptoboy** [comment]
>Could mention that accidentals (sharps/flats) go before notes, not after notes as they do in sheet music.

Sorry, I meant dots (not sharps/flats) "go before notes, not after notes as they do in sheet music"

Reminder to self -- in my PR, I'll probably also mention that some characters stay in effect until changed (O, T, U, X, M, P, W, H, Q, I, S), and some do not (., #, $)

**Comment by dansanderson** [comment]
I have implemented this feedback in the 2nd-edition.
