### ISSUE TITLE
SPRITE command: sprite- vs screen priority correct?

### ISSUE THREAD

**Issue by MauriceMEGA65** [MEGA65/mega65-user-guide#541]
I'm not an expert on this topic, I could be wrong on this one.
I did some playing around with sprites and have the impression that the priority is the other way around in reality.
See attachment.

![Screenshot_2023-06-08_at_23 04 13](https://github.com/MEGA65/mega65-user-guide/assets/75681098/8eff3c95-c6f3-4e51-9d3f-a44e58444dcc)

**Comment by dansanderson** [comment]
Confirmed and corrected in 2nd-edition.
