### ISSUE TITLE
VIC-IV documentation: hot registers

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-user-guide#55]
According to Paul's advice, requesting detailed documentation of all hot registers/bits and the exact effect on other- native VIC IV - registers when writing them.

**Comment by lydon42** [comment]
List of stuff to be added:
- CHARPTR MSB **is not** reset by HOTREG write! (see [mega65-core#308](https://github.com/MEGA65/mega65-core/issues/308) and [mega65-core#368](https://github.com/MEGA65/mega65-core/issues/368))
- SPRPTR MSB **is** reset by HOTREG write! (see [mega65-core#267](https://github.com/MEGA65/mega65-core/issues/267))

**Comment by dansanderson** [comment]
Current text says:

>\item {\bf VIC-II Sprite Pointer Address (\$D06C -- \$D06E, representing a 24-bit address).} This register is reset to the normal location at the end of the screen memory of the current mode.  If the H640 flag is set, then this will be at the end of 2KB screen RAM area, or if the H640 flag is not set, it will point to the end of the 1KB screen RAM area, as on a C64.
> \item {\bf Character Set Base Address (\$D068 -- \$D06A, representing a 24-bit address).}  Note that the hot register function sets only the lower 16 bits of the character set address. That is, \$D06A is not cleared. This is an intentional behaviour, that makes it easier to replace the character set in existing VIC-II-oriented software with another character set in another bank of RAM.

I will assume the two issues mentioned are resolved. Please reopen if you think more changes are needed.
