### ISSUE TITLE
Closing bracket typo in BASIC 65 Operators

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-user-guide#558]
**Describe where we can find the problematic topic**
APPENDIX B
BASIC 65 Command Reference
B-10
One but last line in body text

**Describe the solution you'd like**
"for example A * (A - B) * B) will execute"
... should be ...
"for example A * (A - B) * B will execute"
There is one closing bracket too much.

**Comment by dansanderson** [comment]
Nice catch! Fixed in 2nd-edition.
