### ISSUE TITLE
Unsure about term un-shifted

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-user-guide#559]
**Describe where we can find the problematic topic**
APPENDIX B
BASIC 65 Command Reference
B-10 and B-109
In the section "Remarks", first line

**Describe the solution you'd like**
I am not sure if the term "un-shifted" works here, because the & is a shifted character in my opinion == chars created by pressing a control/shift key in combination with the un-shifted key assignment.
I would change to: "Any ASCII compatible character that is not part of the string can be used instead of /.", because special PETSCII chars do not work but anything else.

**Comment by dansanderson** [comment]
Agreed. Changed to "Any punctuation character", which might be technically inaccurate (if non-punctuation "un-shifted" characters also work) but is the most likely to be useful and understood.
