### ISSUE TITLE
dirname is listed as filename

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-user-guide#560]
**Describe where we can find the problematic topic**
APPENDIX B
BASIC 65 Command Reference
B-46 and B-159
The parameter "dirname" description

**Describe the solution you'd like**
The parameter "dirname" is listed as "filename" in the descriptions of the commands CHDIR and MKDIR.

**Comment by dansanderson** [comment]
Thanks! Fixed in 2nd-edition.
