### ISSUE TITLE
No exact description of CTRL+U

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-user-guide#561]
**Describe where we can find the problematic topic**
APPENDIX C
Special Keyboard Controls and Sequences
C-7
Word movement
CTRL + U

**Describe the solution you'd like**
2 problems:
- The cursor first hits the start of the current word, then the start of previous words
- When we are already on the beginning of a line, we go up one line

The key combi ... 
"Moves the cursor back to the start of the current word, and after that to the start of the previous word or the beginning of the line. From there we jump further up to the previous line."

**Comment by dansanderson** [comment]
I'm not sure how precise this description needs to be, but I took a crack at it anyway:

Ctrl+U: Moves the cursor backward to the start of the previous word. If there is no previous word on the current line, it moves to the first column of the current line, then to the previous line, until a line with a word is encountered.

Ctrl+W: Advances the cursor forward to the start of the next word. If there is no next word on the current line, it moves to the first column of the next line, until a line with a word is encountered.

(Testing this did unearth a bug in the new keyboard scanner, so I'll work on that next. 😅)
