### ISSUE TITLE
Trivial typo Appendix I

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-user-guide#562]
**Describe where we can find the problematic topic**
APPENDIX I
Developing System Programmes
I-5
Introduction
Third paragraph
Last sentence

**Describe the solution you'd like**
"(...) about these programs, how the operate, and the environment (...)" should be "(...) about these programs, how they operate, and the environment (...)".
The word "they" is currently "the".

**Comment by dansanderson** [comment]
Fixed, thanks!
