### ISSUE TITLE
MODKEY bit description is wrong

### ISSUE THREAD

**Issue by Pimau** [MEGA65/mega65-user-guide#568]
**Describe where we can find the problematic topic**
APPENDIX D: The MEGA65 Keyboard
USING THE TYPING EVENT QUEUE
Page D-4
The little table showing the modifier keys bits in MODKEY

**Describe the solution you'd like**
(I have no MEGA65 machine ... maybe it is a XEMU not a documentation bug?)
The documentation says bit 0 is right shift and bit 1 is left shift. It should be the other way around.
I get 1 for left shift, 2 for right shift and 3 for both shifts ... on my Xemu.

Tested with reading the immediate modifier keys from $D611..

**Comment by dansanderson** [comment]
Nice catch! Fixed here: https://github.com/MEGA65/mega65-user-guide/commit/77c8ea1174882046fc0c7c7010997041baeed5f0

Register auto-doc fix is here, will need to be merged by the core team before it shows up in docs: https://github.com/MEGA65/mega65-core/pull/743
