### ISSUE TITLE
Mega65-book > page 12-9 > 6502 instead of 6510 like C64 CPU

### ISSUE THREAD

**Issue by lroby74** [MEGA65/mega65-user-guide#578]
Hello,
like object, on PDF book named Mega65-book, on page 12-9 there is written 6502 instead 6510 like CPU of original C64,
but 6502 is used on Vic20, not on C64.

You can find this typo on this phrase:
"The Commodore 64 and its MOS
6502 CPU use 16-bit addresses to access up to 64 kilobytes (64KB) of memory."

Link for book is this:
https://artifact.mega65.org/static-files/3dXtsnU2iL1wv_EHnn0YW62t89Ph9InxlNBISotdiecxNjk5ODg3MjgyNTgyOjk6YW5vbnltb3VzOmpvYi9tZWdhNjUtdXNlci1ndWlkZS9qb2IvbWFzdGVyL2xhc3RTdWNjZXNzZnVsQnVpbGQvYXJ0aWZhY3Q=/mega65-book.pdf

**Comment by dansanderson** [comment]
Re-worded.

In general, I'm not inclined to explain the distinction between 6502 and 6510 unless it is relevant. Most discussions of the 45GS02 CPU are best served by referring to the 6502 as the first CPU in the lineage.
