### ISSUE TITLE
Basic 65 reference says DS is cleared automatically

### ISSUE THREAD

**Issue by fredrikr** [MEGA65/mega65-user-guide#590]
**Describe where we can find the problematic topic**
The documentation on the DS system variable in the Basic 65 reference says "Reading the disk status from a disk device automatically clears any error status on that device, so subsequent reads will return 0, if no other activity has since occurred."

This is not correct. E.g. if you get an error 62 (file not found) from U8, you can read DS over and over again and still get 62.

**Describe the solution you'd like**
Describe that users need to do `CLR DS` to clear the value.

**Describe alternatives you've considered**
Maybe the DS variable should indeed be cleared automatically, as described?

**Additional context**
-

**Comment by johnwayner** [comment]
Related rom issue that changed this behavior: https://github.com/MEGA65/mega65-rom-public/issues/85
