### ISSUE TITLE
Chipset Ref. typo

### ISSUE THREAD

**Issue by uffdaken** [MEGA65/mega65-user-guide#592]
In the Mega65 Chipset Ref. manual, Pg. 10 under "CPU Memory Banking". It begins with "The 45GS10 processor...."

Then on page 27, under "Bad Lines" 2nd. paragraph it states "The 45GS02 processor of the Mega65...." 45GS02 is mention to more times in this paragraph.

Also on page 122 under "Debugging and Diagnostics Features", 4th. paragraph, there are three instances where "45gs02" is in lower case.

I am assuming that this might be the case with the other manuals.

**Comment by dansanderson** [comment]
Fixed, thanks!

The official name of the CPU is "45GS02," and there isn't enough value in adopting the conventional "10" distinction for system-on-a-chip packages in our case to use both and confuse readers. (If there's ever an ASIC that implements the 45GS02 along with other devices, we can call it 45GS10. :) )
