### ISSUE TITLE
Improving the diagram for the MAP instruction

### ISSUE THREAD

**Issue by Rhialto** [MEGA65/mega65-user-guide#599]
**Describe where we can find the problematic topic**

appendix-45gs02-registers.tex \subsubsection{The MAP instruction}

**Describe the solution you'd like**

The diagram shows `LDZ #$XA` and `LDX #$ZD`.
The `LDZ` points to some split up bits: `X7...X4`.
The `LDX` points to some split up bits: `Z7...Z4`.

Since both X and Z are register names, this is confusing.

**Describe alternatives you've considered**

Use `LDZ #$ZA` and `LDX #$XD` and adjust the vertical bitmap to use from top to bottom `Z7` ... `Z4`, `X7`...`X4`.

**Additional context**

If this is incorrect I misunderstood the illustration and it should be fixed in some different way :-)

**Comment by dansanderson** [comment]
You are correct, this would be an improvement. I believe this suggestion is what was intended. Will fix.
