### ISSUE TITLE
The screenoutput environment can be broken across pages, with single lines of text on one page or the other.

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#6]

**Comment by sausagejohnson** [comment]
@gardners not 100% sure what the expected output should be if a code listing spreads from one page to another. RIght now, it breaks and continues correctly across pages.

The commdore 128 manual has listings in a couple of formats. One is a monospaced font where the listing is surrounded by a keyline. An example of it splitting over two pages is on 7-28 to 7-29.

No examples of the other listing type. Listings were always very short, so never broke over pages.

There is an example in the Commodore 64 manual page 81 - 82.

**Comment by Edilbert** [comment]
I think, this is not really a bug. If it is important, to keep lines together, one could put the screen output into a \minipage. I suggest, that we close this issue.

**Comment by sausagejohnson** [comment]
Agreed.

**Comment by gardners** [comment]
I think my concern was orphan and widow lines in the screenoutput environment.  I don't mind listings with a few lines on each of 2 pages, but we should never have a single line on a page, when the rest is on another page.  So I think there is still a bug we should fix here. I'm quite fine with using minipage as the solution, if that is what we decide.

**Comment by Edilbert** [comment]
I included the package:
\usepackage[all]{nowidow}
