### ISSUE TITLE
VIC-IV documentation: detailed list of all VIC registers in all VIC modes

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-user-guide#61]
According to Paul's advice, requesting detailed documentation of all VIC-IV registers there exact meaning also in different VIC modes.

**Comment by gardners** [comment]
In theory, this should already be in the mega65-book.pdf buildable from this repository, in the appendix dealing with the VIC-IV.  If there are particular registers lacking sufficient documentation, please file an issue for each.
