### ISSUE TITLE
BASIC ref : syntax SCREEN DEF incorrect

### ISSUE THREAD

**Issue by pchnl** [MEGA65/mega65-user-guide#618]
In the BASIC manual, page 225 it shows syntax:
SCREEN DEF width flag, height flag, depth (in the Format: after Token: at top).

I believe that should be : 
SCREEN DEF screen, width flag, height flag, depth

SCREEN DEF 0,0,2 gives: ? ILLEGAL QUANTITY ERROR
SCREEN DEF 1,0,02 gives: READY

**Comment by dansanderson** [comment]
Fixed, thank you!
