### ISSUE TITLE
VIC-IV documentation: VIC-level timing like bad line condition

### ISSUE THREAD

**Issue by lgblgblgb** [MEGA65/mega65-user-guide#62]
According to Paul's advice, requesting detailed documentation of exact timing of different VIC modes for PAL and NTSC, now not the native VGA video mode behind but the VIC-level, like "bad line" condition and similar things if there are more, also I would like to know if there are any different between video modes or they are always at every 8th line?

Bonus question: is badline timing is VIC-II specific? I guess it's not so much use to slow things down for M65 (non-legacy) software, so it can be useful to turn that off, by default in VIC-IV mode, or at least via some register thus optionally.

**Comment by gardners** [comment]
I'll work on some diagrams for this, as well as some explanation in the text.

The badlines are optional on the MEGA65.  I'll document the CPU register that enables them.  They also don't work ever when the CPU is at full speed, so normally there is no need to fiddle with this setting, but it is helpful for users to be aware of it.

Badlines can be moved, just as on the VIC-II by fiddling with the smooth scroll bits in $D011.

Please let me know if the documentation is sufficient for you now (apart from the missing diagram).

**Comment by lgblgblgb** [comment]
Btw for "things like" bad line condition I even have extra cycles needed by VIC-II in case of sprite fetch ... I'm not sure it's implemented for compatibility on mega65, or is there any similar for non-VIC-II things (like even VIC-IV mode with VIC-IV specific things, probably requiring much more 'extra' fetch than VIC-II should do because-of/in-case sprites)  where CPU should be stopped because of extra memory access.

**Comment by gardners** [comment]
True. I haven't put the sprite badline penalty in there either.
But none of the VIC-III/IV things cause any time robbery from the CPU, because the VIC-IV has dual-port access to all of the memory it needs.  So it is only the VIC-II badline emulation that is required.  
Please file a bug on mega65-core asking for sprite fetch penalty in badline emulation.  I'll in the meantime update the documentation to indicate that sprite fetch doesn't currently affect badline timing.

**Comment by gardners** [comment]
@lgblgblgb let me know if there are still things we haven't covered for you.

**Comment by gardners** [comment]
I think the core material for this one is done now.
