### ISSUE TITLE
Fonts derived from Glacial Indifference require updated meta-data

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#63]
We need to modify the meta-data in these fonts, so that they really are a unique typeface.  This should be done in any case, but in the short term the problem it causes is that we can't use Mega Glacial instead of Galcial Indifference in Inkscape to draw diagrams with text in the correct font on them.

**Comment by gardners** [comment]
Edilbert: Would you be able to tackle this one?
Thanks,
Paul.

**Comment by Edilbert** [comment]
Hi Paul,
I edited the meta data following the rules of the "Open Font License"
[https://scripts.sil.org/OFL](url)
The copyright holder of the derived font is now M.E.G.A., the original designer Alfredo Marco Pradil is acknowledged.
I hope, that everything is now clean and legal.
So far I edited the Regular fontface only.
If I get an OK from you, I'll edit the bold and italic fontface too.
Edilbert

**Comment by gardners** [comment]
Hello,

Yes, that sounds perfect to me.
Please do the others as well.

Paul.

**Comment by Edilbert** [comment]
All three font files are updated.
