### ISSUE TITLE
Screen font with scan lines ?

### ISSUE THREAD

**Issue by Edilbert** [MEGA65/mega65-user-guide#64]
I created a second screen font, that emulates scan lines.
Which one do you like better?
<img width="665" alt="Solid" src="https://user-images.githubusercontent.com/6380947/69484829-11ee2a80-0e38-11ea-99b0-da0aa23e1c80.png">
<img width="665" alt="Scanlines" src="https://user-images.githubusercontent.com/6380947/69484830-1581b180-0e38-11ea-9c53-f0a53caf7b4f.png">

**Comment by sausagejohnson** [comment]
Personally non-scan lines for a book. I do like the font though. Might be good for creating promo material.

**Comment by gardners** [comment]
Hello,

I think I agree -- unless there are places in the book where we really want
to refer to content on the screen, where the on-screen context is
important. It does look really nice, though :)

Paul.

**Comment by Edilbert** [comment]
OK, the survey here and at the forum64 gave a clear result.
The solid font is preferred to the CRT like.

Now I want your opinion on colouring the screen output:
Here are three examples:
1) MEGA65 default colours
<img width="543" alt="Blue" src="https://user-images.githubusercontent.com/6380947/69553281-39f89d80-0fa0-11ea-9cd7-1d339ced4d71.png">

2) PET/CBM style
<img width="543" alt="Green" src="https://user-images.githubusercontent.com/6380947/69553354-5ac0f300-0fa0-11ea-8dd3-391b83d4ee2a.png">

3) White on black
<img width="543" alt="White" src="https://user-images.githubusercontent.com/6380947/69553393-6d3b2c80-0fa0-11ea-8243-a3384600fd9c.png">

**Comment by sausagejohnson** [comment]
Black and white if cost is reduced for printing, as colour would be much more. Also appears the easiest on the eyes.

If colour, maybe the blue?

**Comment by gardners** [comment]
Hello,

Yes, I think the blue or white versions make the most sence. But perhaps
ask more widely, e.g., on F64 what people think.

Paul.

**Comment by Edilbert** [comment]
If I may summarize the (low) feedback from here and the forum64:
1) Green on black got some praises for retro feeling and readability, but this colour scheme is not related to the C65/MEGA65.
2) White on blue is the default MEGA65 colour scheme, but less eye friendly.
3) White on black seems to be the best compromise, so we should stay with that.

Then I wanted to implement reverse printing and ran into several problems:
Creating reverse characters is not a solution, because the listing environment puts extra space between the character cells, and this space is not inverse. That would look terrible.
I found no solution for printing reverse in the listing environment, I think, it is not implemented.
So I changed from listing environment to a combination of \tcolorbox and \verbatim.
See the examples below. I think the new design (top panel) is more authentic.
What do you think?
<img width="668" alt="Snippet" src="https://user-images.githubusercontent.com/6380947/69745526-a90df780-1142-11ea-9786-a302d3991e2c.png">

**Comment by sausagejohnson** [comment]
It does look good and I can't remember why I abandoned my earlier attempts to use tcolorbox with the listings. There was some glitch I couldn't resolve with it. Might need a complete character map test to ensure no artifacts or weirdness. But if it turns out to be all good, you have a nice solution there.

**Comment by Edilbert** [comment]
Here is a character test:
<img width="433" alt="Chars" src="https://user-images.githubusercontent.com/6380947/69762543-da9ab900-116a-11ea-9006-817606a8a952.png">
And the LaTeX source:
<img width="496" alt="Latex" src="https://user-images.githubusercontent.com/6380947/69762611-12096580-116b-11ea-9e30-7e75c607f137.png">

**Comment by sausagejohnson** [comment]
The character test is spacing your chars out a little. Which I think is a problem I had. But your listing has them correct.

**Comment by Edilbert** [comment]
Here is a character test with no spaces:
<img width="421" alt="Narrow" src="https://user-images.githubusercontent.com/6380947/69763354-36664180-116d-11ea-8f7c-74984c5ef52b.png">

I assume, you did the early test with the PETME-Font?
Maybe, the problems are gone, because we now use my font,
which is completely new created.

**Comment by sausagejohnson** [comment]
Nice. Yes I agree. I was fighting with an early font and had lots of issues. Looks like these are gone. Might be worth adding inverse chars, petscii chars to the character test too?

Then we have full coverage.

**Comment by Edilbert** [comment]
This is my plan. Currently I think about, how to map graphic characters and reverse characters into the unicode. Would be nice, if they can be entered with a standard editor like vim or emacs.
Of course they will look different in the editor. We already have some examples, like the backslash, circumflex, underline and tilde which are mapped to the CBM characters pound, uparrow, backarrow and pi. Proposals are welcome.

**Comment by gardners** [comment]
Hello,

Looks good to me. Well done!

Paul.

**Comment by sausagejohnson** [comment]
It was interest that in the manual, I could paste the characters in directly. But they looked different in the code. Made it a little tricky.

But well done on improving this component!!!

**Comment by gardners** [comment]
Hello,

Would it make sense to have the reverse version of the font as "bold", so
you can just use {\em ... } to get reverse text?

Paul.

**Comment by Edilbert** [comment]
This is a good idea. I'll create a "bold" font for reverse characters and an "italic" font for graphics.
{\bf} and {\em} can't be used inside the verbatim block, but there are many other occasions, where these fonts may come handy.

**Comment by Edilbert** [comment]
I chose a code range for the graphic symbols, that is mapped to printable characters in UTF8 encoding ($C380 - $C3BF) = display code ($40 - $7F) on PET/CBM. This is not comfortable, but it works until someone finds a better solution.
The expanded screen font "mega80":
<img width="178" alt="PETSCII" src="https://user-images.githubusercontent.com/6380947/69953524-b38d1000-14f9-11ea-9e6f-b68064526f3e.png">
This is the UTF8 mapping (how they are shown in the editor):
<img width="162" alt="UTF8" src="https://user-images.githubusercontent.com/6380947/69953560-c869a380-14f9-11ea-9236-e3a6e1369273.png">

**Comment by Edilbert** [comment]
The full character set is now at your fingertips.
There are two font files:
mega80-Regular.ttf
mega80-Reverse.ttf
They are defined in the LaTeX source as \codefont.
The reverse font is handled like an italic font.

{\codefont
print normal or {\em reverse}
}

<img width="208" alt="Bildschirmfoto 2019-12-04 um 17 53 13" src="https://user-images.githubusercontent.com/6380947/70163322-8db16800-16bf-11ea-9c68-81fb6d581482.png">
