### ISSUE TITLE
Basic statements XOR(arg1, arg2) and MOD(arg1, arg2)

### ISSUE THREAD

**Issue by mds75** [MEGA65/mega65-user-guide#66]
Just looked through the BASIC 10 Command Reference in the user guide. 

XOR statement write-up is missing.
So PRINT(XOR(128,64)) should output a result of 192, say. (toggles the bits)
 
Also, I think that the statement MOD (for modulo arithmetic) is undocumented (i,e, it's not in the system manual) but it *is* implemented.
So PRINT(MOD(128,64)) should output a result of 57, say.

Do we want to include write-ups of these statements too?

**Comment by gardners** [comment]
Yes,  please document them, but note your MOD example is not correct (as
just tested on a M65).

Paul.

**Comment by Edilbert** [comment]
MOD and XOR are added to the BASIC-10 command reference chapter
