### ISSUE TITLE
Text processing, Strings and Characters Chapter

### ISSUE THREAD

**Issue by mds75** [MEGA65/mega65-user-guide#67]
I'd like to write a chapter on BASIC string processing, such as how to use LEFT$, RIGHT$, MID$ etc. as well as some simple example programs that involve text.

For example, splitting a long string into words at white-space (tokenizing), changing case and using the PETSCII characters etc.

I think that this would be advantageous for beginners, since most simple program require some form of text output.

What else should we include? Suggestions welcome. I can get started on this right away. I expect that it would be about 20-30 pages in length.

**Comment by sausagejohnson** [comment]
This might be good as part of a chapter on variables in general. So integers, and then strings?

20-30 pages would be very very long for the manual.

**Comment by Edilbert** [comment]
This is a good idea. I suggest to combine it with a detailed description of PRINT USING.
In BASIC dialects, which did not have the PRINT USING, the string functions were mainly used, to produce neatly formatted output, which can be done with PRINT USING in BASIC-10.

**Comment by gardners** [comment]
Hello,

Produce the material, and we can decide if it is too long or not at that
point. Also where it should go.
In theory, I have a student who this week should be producing some examples
with numbers and things, so leave that for a little bit, to see what they
produce.  But the complex string handling stuff would be great.

Paul.

**Comment by mds75** [comment]
Hi Paul, 

 

I noticed you closed this issue. I’m still working  on the chapter for text stuff.

 

Admittedly it’s taking me a bit long to do this, so apologies for that.

 

I’ve done the following:

 

1.	Simple explanation of String and characters in Basic, including a motivation of why text is important.
2.	String Literals and String Variables (includes concatenation and input like INPUT, GET and GETKEY)
3.	One  example that uses text to check a string for a palindrome (words that read forwards and backwards the same)
4.	Another example that uses three simple ciphers to encrypt strings using Caesar cipher, Atbash cipher and ROT13 cipher. Contains an example program.

 

So far, it’s about 13 pages of stuff.

 

I have yet to add to it the following:

1.	Behaviors (with examples) of string statements (like MID$ and LEFT$, RIGHT$, STR$, ERR$ TI$ etc)
2.	Formatting with TABS and SPACES using TAB and SPC
3.	PRINT USING and PUDEF
4.	Maybe an example of drawing up tables in text

This other stuff might take up 7 pages, for 20 pages in total.

 

If you would like me to continue doing this then I’m currently free to do so. I can finish it within about 1 week if need be.

 

(I’ve still  been following the blog, and still enthusiastic about the project but I have been a bit busy with other things – sorry)

 

Please let me know.

 

Thanks 

Mark

**Comment by gardners** [comment]
I think I clicked in the wrong place. Please continue!

**Comment by gardners** [comment]
(Also ignore that mis-classified commit against this issue above. That was me getting #76 round the wrong way :/ )

Looking forward to seeing what you have produced, when you get it ready :)

**Comment by mds75** [comment]
Phew! Thanks for that 😊

 

It’s been sitting in my “todo list” for sometime now. I’ll get on to it.

By next week I’ll have something ready to show.

 

Mark

**Comment by gardners** [comment]
That sounds great! The MEGA65 Book has been advancing nicely in recent weeks, and your piece will help fill a big hole. It's close to 550 pages already.

Paul

**Comment by gardners** [comment]
How are you progressing? Anything we can help out with?

**Comment by mds75** [comment]
Hi Paul,

 

I’ve edited my manuscript recently. It’s about 16 pages now, so only 4 pages to go.

(I had to add some extra information on modular arithmetic for the simple cryptography examples so that they will make more sense to those not versed in such topics.)

 

Mostly, I’ve got left  some simple stuff—like some examples that use LEFT$ and RIGHT$ to print all left and right substrings of an input string.

 

I’ll have something ready for you to look at by this Friday.

 

Cheers,

 

Mark

**Comment by gardners** [comment]
Ok, I've merged your pull request in.  Is there more on this you have planned?

**Comment by mds75** [comment]
Hi,

 

Thanks for merging it in, Paul. It might be best if someone else proofreads the chapter for clarity and correctness and makes the necessary formatting changes, if needed.

 

I have nothing else to add to the chapter.

 

At this stage, my technical writing skills are probably better spent in reviewing what others have already written. I will  suggest potential changes to the document if I find anything amiss or that needs clarification.

 

Thanks

 

Mark

**Comment by gardners** [comment]
Thanks, and will do some proof-reading over it when I get a moment.
