### ISSUE TITLE
Lots of undefined control sequence errors during typesetting

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#7]
Eg:

> ! Undefined control sequence.
> <argument> ...ne {\textbullet }\gobble@numberline
>                                                   \hyper@linkstart {link}{\H...
> l.14 ...t a pile of switches}{18}{section*.5}}{14}

**Comment by sausagejohnson** [comment]
Picking this up.

**Comment by sausagejohnson** [comment]
Hi Paul get I get contributor access to the repo so I can assign tasks  
to myself? That way we can track what job I am working on (so there's  
no double handling)

Quoting gardners <notifications@github.com>:

**Comment by sausagejohnson** [comment]
This is a really frustrating one. Essentially the following code is functional, but gives the above mentioned error:

\newtcbox{\megakey}[1][small]{colback=black, coltext=white, size=#1, fontupper=\bfseries\uppercase,nobeforeafter,box align=bottom,text height=7pt}

I can fix this by breaking the component up into an inner key like so:

\newtcbox{\megakeyinner}[1][small]{colback=black, coltext=white, size=#1, fontupper=\bfseries, nobeforeafter,box align=bottom,text height=7pt}
\newcommand{\megakey}[2][small]{\megakeyinner[#1]{\uppercase{#2}}}

This works, and the error goes away in isolated tests.

But when applying to the main document, errors return. There is obviously conflict with other libraries or content.

Next step for me is to work out what the conflict is by the process of elimination, however, I am wondering if we look to another typesetting system. Latex/XeTex just seems so antiquated and every thing we do is more difficult than it needs to be.

**Comment by gardners** [comment]
I agree latex is a bit old-school, but I am concerned about learning curve of switching, and that we may even then hit some weird problem(s).  Basically while I am a major contributor of content -- which I don't see changing in the near future -- the cost of switching would seem to me to outweigh the problems with latex. Indeed, this issue is really just an annoyance, rather than stopping us using it.

**Comment by gardners** [comment]
Also occam's razor could be used to work out which packages conflict, or which parts of the main document tickle it.  Annoy, I grant, but not impossible.

**Comment by Edilbert** [comment]
Resolved by removing the redefinition of l@section, which seems not to be necessary, but introduces conflicts with hyperref:

\renewcommand*{\l@section}[1]{%
\@dottedtocline{1}{1.0em}{1em}{%
\numberline{\textbullet}%
\numberline{$\cdot$}%
\gobble@numberline
#1%
}}
