### ISSUE TITLE
Register Table Importer needs to know about 28 bit addresses

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#70]
Decimal addresses >64K are too wide for the "decimal" column. These occur in only a few tables, so we shouldn't make the decimal table always be wider.  The table generator should detect when it is required, and make the necessary change to column widths.

**Comment by dansanderson** [comment]
It looks like only `regtable_RTC.MEGA65.tex` and `regtable_SUMMARY.MEGA65.tex` have addresses larger than 64K, and neither of these files are currently included in any document.

Nevertheless, I added logic to drop the DEC column if any register address in the table is >64K, and to widen the HEX column. This could easily be adjusted to simply widen both HEX and DEC, but I figure a DEC address >64K is very much useless.

This doesn't resolve issues with over-wide signal names. Maybe we could use similar conditional logic based on the character length of the signal name in each column, but just as likely we either don't document the really long ones or come up with shorter names.

[sandbox.pdf](https://github.com/user-attachments/files/16152356/sandbox.pdf)
