### ISSUE TITLE
40-column screen text ?

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#72]
It would be great if we can add a 40-column screen text macro, for showing what screens will look like in c64 mode or 40-column mode.  Ideally it would be possible to have different colour text etc. For example, it would be nice to be able to show screenshots for the core / flash menu.

**Comment by sausagejohnson** [comment]
@gardners Given that there was a decision(?) to not try and cover C64 modes and output in the new manual, can this be closed. Or is there still some value to doing this?

**Comment by gardners** [comment]
Implemented \screentextwide for 40-column width text when required in text for clarity.

**Comment by Edilbert** [comment]
I scaled the screenfont "mega80-Regular.ttf" by duplicating the character width
and added it to the font directory as "mega40-Regular.ttf".

So you have now the choice of using:

\verbatimfont{\codefont}

or \verbatimfont{\codefontw}

Best wishes,
Edilbert

**Comment by gardners** [comment]
Thanks. I did manage to get in the STYLE C64 TTF font in the meantime.  Feel free to remove that one and use the one you have provided for consistency.  

I've also tweaked the screenoutput and screentext macros to give the choice of thin or fat screen text, and to provide simpler macros for these which I am using in the beginningbasic.txt file.

Paul.
