### ISSUE TITLE
Too early for proofreading / PRs?

### ISSUE THREAD

**Issue by woepaul** [MEGA65/mega65-user-guide#74]
Over the weekend I built myself `mega65-book.pdf` from master and read it from top to bottom since I was curious about Basic 10 and the MEGA65 hardware. Overall a pleasant experience. I learned a lot. While it already looks polished in many places I found rough edges here and there (not counting the chapters that are simply not there yet).

Do you consider it valuable if I create PRs for the places that need fixing / improvement or is it still too early for that?

The MEGA65 is fantastic. I follow it from it's beginning (& donated twice). The system has so many cool features (math unit, hypervisor, DMA controller, new VIC modes, ...). Without solid documentation the MEGA65 is at risk of not getting used to its full potential.

**Comment by gardners** [comment]
Hello,

We are so glad that you are finding pleasure in what we are createing. This is the main purpose of the MEGA65!

We completely agree that excellent documentation is vital for the MEGA65, and so we would of course welcome issues and pull-requests to improve things, or even provide material for some of the missing/empty chapters.  It's never too early for this, and certainly now now that we have close to 500 pages of material.
