### ISSUE TITLE
4510GS CPU Opcodes section missing

### ISSUE THREAD

**Issue by deftmega** [MEGA65/mega65-user-guide#76]
I am missing a full list of 4510GS opcodes with samples. BASIC is nice but assembly language is nicer :)

**Comment by gardners** [comment]
Yes, we need both 6502 and 4510 Opcode lists.  I'll have a think about how I can automate the generation of this section as much as possible.

**Comment by gardners** [comment]
Begun implementing automatic way to generate all this from instruction descriptions and opcode lists.  Still many undocumented instructions, and some cycle counts will be wrong, which will need to be checked.  Also much of the surrounding work for showing what the footnotes for cycle counts mean etc are not there.

**Comment by gardners** [comment]
All done.
