### ISSUE TITLE
Memory map missing

### ISSUE THREAD

**Issue by Taygair** [MEGA65/mega65-user-guide#77]
It would be great to have an overview where is what:
- memory addresses (Sprites, display, VIC-IV, ports, etc.)
- registers
- ...

Kinda lookup list for Assembler devs

**Comment by gardners** [comment]
Please check Appendix E "System Memory Map" and tell me if it contains all the information you require. If not, please let me know what you hoped to find, but could not find.

**Comment by gardners** [comment]
(Note this appendix may only be in MEGA65 Book, not MEGA65 User Guide).

**Comment by Taygair** [comment]
Hi Paul 

I have already added an issue:
-> Address/memory/register list

That goes together with Detlefs issue concerning OPCode list.

Farai

**Comment by gardners** [comment]
ok. Will look. So we can close this one, then?

**Comment by Taygair** [comment]
Which „this one“?

If anything of this is in the book then yes…. :o)

**Comment by gardners** [comment]
Ok, memory map fixups are the last of this. If there are parts we have missed, then they can get filed as new issues.
