### ISSUE TITLE
Problem with \megakey macro?

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#8]
Lots of errors like this when typesetting:

> ! Missing } inserted.
> <inserted text>
>                 }
> l.296 ...} \megakey{Run/Stop} \megakey{\leftarrow}
>                                                    \megakey{\uparrow} \megak...

**Comment by sausagejohnson** [comment]
Please assign to me

**Comment by gardners** [comment]
Better yet, I just added you as a collaborator, so you should be able to assign yourself now :)

**Comment by sausagejohnson** [comment]
Thanks Paul.

Wayne

Quoting gardners <notifications@github.com>:

**Comment by gardners** [comment]
My pleasure!

Paul.

**Comment by sausagejohnson** [comment]
Fixed with #12
