### ISSUE TITLE
ASCII CODES has items that take up two lines when rendered to MEGA65-Book_draft.pdf

### ISSUE THREAD

**Issue by woepaul** [MEGA65/mega65-user-guide#81]
I recently contributed e2f31449fbf21e85e38f93c85af65c5d99f3c752

When building the table locally with `make` the resulting table looked fine. Now I see that in the recently regenerated https://github.com/MEGA65/mega65-user-guide/commits/master/MEGA65-Book_draft.pdf unfortunately the table has entries that take up two lines. These are
https://github.com/MEGA65/mega65-user-guide/blob/9d03e239a26d6fb439dc121c01d51b1c684e8ff8/appendix-asciicodes.tex#L29
https://github.com/MEGA65/mega65-user-guide/blob/9d03e239a26d6fb439dc121c01d51b1c684e8ff8/appendix-asciicodes.tex#L30
and
https://github.com/MEGA65/mega65-user-guide/blob/9d03e239a26d6fb439dc121c01d51b1c684e8ff8/appendix-asciicodes.tex#L151

This looks ugly. It would be nice if @Edilbert could tweak those lines so that in the generated MEGA65-Book_draft.pdf the corresponding items only require single lines.

TIA, woepaul

**Comment by woepaul** [comment]
https://github.com/MEGA65/mega65-user-guide/blob/9d03e239a26d6fb439dc121c01d51b1c684e8ff8/appendix-asciicodes.tex#L162 also has the same problem.

**Comment by Edilbert** [comment]
fixed
