### ISSUE TITLE
Esc sequence description

### ISSUE THREAD

**Issue by dikdom** [MEGA65/mega65-user-guide#85]
"Escape sequences are performed a little differently than a Control function or a Shifted
function. Instead of holding the modifier key down, an Escape sequence is performed by
pressing the ESC key once, then pressing the desired key code."

1) One paragraph earlier it was stated it is called 'Shift Function', why it is called here 'Shifted function'?
2) I would stress a bit more that the ESC key has to be released before pressing the second key (in the sequence). Like "pressing the ESC key once (and release it)"

**Comment by gardners** [comment]
Thanks for the proof-reading, change incorporated.
