### ISSUE TITLE
prg2tex should produce upper-case output and use \screenoutput

### ISSUE THREAD

**Issue by gardners** [MEGA65/mega65-user-guide#86]
Currently the output is in the 8-bit font, but listings appear in lower-case, and without the white-on-black text box

**Comment by gardners** [comment]
I figured out the white-on-black by wrapping in a tcolorbox etc, but the listings still appear in lower-case.  Having the option to select upper or lower case would still be welcome.

**Comment by Edilbert** [comment]
You are free to use upper case and graphic symbols in the listings.
The font supports all PETSCII characters.
Or is your request, that the program prg2latex should have a upper case option ?
I can implement that.

Edilbert

**Comment by gardners** [comment]
Yes, that it have an option for upper case output.
The tool is simply fantastic, though! I had almost forgotten that you had made it, was about to start thinking about how I was going to cook one up, and then I was reminded of the joy of us all working together as a team on this machine :)

**Comment by Edilbert** [comment]
I added the option '-u' for upper case program listings in LaTeX.
It's not an 8-bit font though, but an UTF8 font, only the characters 0x00 -> 0x7f are 8bit.
I don't understand the meaning of "\screenoutput #86" in your request.

**Comment by gardners** [comment]
Thanks! I'll take a look, and separately comment on #86 for you.

**Comment by gardners** [comment]
Looks great, thanks!

**Comment by gardners** [comment]
ok, ignore the \screenoutput thing. I had figured that out separately.
